GLOBAL_LIST_INIT(broken_floor_states, list(
	"abductor" = list("alienpod1_dam"),
	"carpet" = list("damaged"),
	"common" = list("common-broken1","common-broken2","common-broken3","common-broken4","common-broken5","common-broken6"),
	"common_dark" = list("common_dark-broken1","common_dark-broken2","common_dark-broken3","common_dark-broken4","common_dark-broken5","common_dark-broken6"),
	"common_light" = list("common_light-broken1","common_light-broken2","common_light-broken3","common_light-broken4","common_light-broken5","common_light-broken6"),
	"diamond" = list("diamond_dam"),
	"fakespace" = list("damaged"),
	"fancy" = list("fancy-broken1","fancy-broken2","fancy-broken3","fancy-broken4","fancy-broken5","fancy-broken6"),
	"fancy_dark" = list("fancy_dark-broken1","fancy_dark-broken2","fancy_dark-broken3","fancy_dark-broken4","fancy_dark-broken5","fancy_dark-broken6"),
	"fancy_light" = list("fancy_light-broken1","fancy_light-broken2","fancy_light-broken3","fancy_light-broken4","fancy_light-broken5","fancy_light-broken6"),
	"generic" = list("damaged1", "damaged2", "damaged3", "damaged4", "damaged5"),
	"gold" = list("gold_dam"),
	"grass" = list("sand"),
	"housebase" = list("housebase1-broken", "housebase2-broken", "housebase3-broken", "housebase4-broken"),
	"housecarpet" = list("torncarpet1", "torncarpet2", "torncarpet3", "torncarpet4", "torncarpet5", "torncarpet6", "torncarpet7", "torncarpet8", "torncarpet9", "torncarpet10", "torncarpet11", "torncarpet12", "torncarpet13", "torncarpet14", "torncarpet15", "torncarpet16", "damaged1"),
	"houseinterior" = list("housewood-dam1", "housewood-dam2", "housewood-dam3", "housewood-dam4", "housewood-dam5"),
	"housewood" = list("housewood1-broken", "housewood2-broken", "housewood3-broken", "housewood4-broken"),
	"light" = list("light_broken"),
	"mosaic" = list("mosaic-broken1","mosaic-broken2","mosaic-broken3","mosaic-broken4","mosaic-broken5","mosaic-broken6"),
	"mosaic_dark" = list("mosaic_dark-broken1","mosaic_dark-broken2","mosaic_dark-broken3","mosaic_dark-broken4","mosaic_dark-broken5","mosaic_dark-broken6"),
	"mosaic_light" = list("mosaic_light-broken1","mosaic_light-broken2","mosaic_light-broken3","mosaic_light-broken4","mosaic_light-broken5","mosaic_light-broken6"),
	"noslip" = list("noslip-damaged1","noslip-damaged2","noslip-damaged3"),
	"plasma" = list("plasma_dam"),
	"plasteel" = list("damaged1", "damaged2", "damaged3", "damaged4", "damaged5"),
	"plastitanium" = list("plastitanium_dam1","plastitanium_dam2","plastitanium_dam3","plastitanium_dam4","plastitanium_dam5"),
	"plating" = list("platingdmg1", "platingdmg2", "platingdmg3"),
	"rockcrete" = list("rockcrete_slab_dmg1", "rockcrete_slab_dmg2", "rockcrete_slab_dmg3", "rockcrete_slab_dmg4"),
	"silver" = list("silver_dam"),
	"snow" = list("platingdmg1", "platingdmg2", "platingdmg3"),
	"titanium" = list("titanium_dam1","titanium_dam2","titanium_dam3","titanium_dam4","titanium_dam5"),
	"titanium_old" = list("titanium_dam1_old","titanium_dam2_old","titanium_dam3_old","titanium_dam4_old","titanium_dam5_old"),
	"uranium" = list("uranium_dam"),
	"wide" = list("wide-broken1","wide-broken2","wide-broken3","wide-broken4","wide-broken5","wide-broken6"),
	"wide_dark" = list("wide_dark-broken1","wide_dark-broken2","wide_dark-broken3","wide_dark-broken4","wide_dark-broken5","wide_dark-broken6"),
	"wide_light" = list("wide_light-broken1","wide_light-broken2","wide_light-broken3","wide_light-broken4","wide_light-broken5","wide_light-broken6"),
	"worn" = list("worn-broken1","worn-broken2","worn-broken3","worn-broken4","worn-broken5","worn-broken6"),
	"worn_dark" = list("worn_dark-broken1","worn_dark-broken2","worn_dark-broken3","worn_dark-broken4","worn_dark-broken5","worn_dark-broken6"),
	"worn_light" = list("worn_light-broken1","worn_light-broken2","worn_light-broken3","worn_light-broken4","worn_light-broken5","worn_light-broken6")
))

GLOBAL_LIST_INIT(burnt_floor_states, list(
	"housebase" = list("housebase_burnt"),
	"housecarpet" = list("damaged"),
	"noslip" = list("noslip-scorched1","noslip-scorched2"),
	"plasteel" = list("floorscorched1", "floorscorched2"),
	"plating" = list("panelscorched"),
	"snow" = list("snow_dug")
))
