/*ALL DEFINES RELATED TO AMMO GO HERE*/

//Caliber defines
#define CALIBER_22LR ".22LR rounds"
#define CALIBER_5MM "5mm rounds"
#define CALIBER_556 "5.56mm / .223 rounds"
#define CALIBER_762 "7.62mm / .308 rounds"
#define CALIBER_9MM "9mm rounds"
#define CALIBER_10MM "10mm rounds"
#define CALIBER_14MM "14mm rounds"
#define CALIBER_38 ".38 special rounds"
#define CALIBER_357 ".357 magnum rounds"
#define CALIBER_44 ".44 magnum rounds"
#define CALIBER_45LC ".45 LC rounds"
#define CALIBER_45ACP ".45 ACP rounds"
#define CALIBER_4570 ".45-70 rounds"
#define CALIBER_50MG ".50MG rounds"
#define CALIBER_2MM "2mmEC gauss slugs"
#define CALIBER_SHOTGUN "12 gauge shells"
#define CALIBER_CASELESS "4.73mm caseless"
#define CALIBER_75 ".75 gyrojets"
#define CALIBER_195 "1.95mm rounds"
#define CALIBER_712 "7.12mm rounds"
#define CALIBER_40MM "40mm rounds"
#define CALIBER_MAGNETIC "magnetic rounds"
#define CALIBER_MAGNETIC_HYPER "hypermagnetic rounds"
#define CALIBER_MUSKET_BALL "musket balls"
#define CALIBER_MUSKET_LASER "laser musket packs"
#define CALIBER_MUSKET_PLASMA "plasma musket packs"
#define CALIBER_NEEDLE "needles"
#define CALIBER_ROCKET "rockets"
#define CALIBER_SPEAR "speargun rounds"
#define CALIBER_LASERGATLING "laser gatling charges"
#define CALIBER_LASER "oldlasers"
#define CALIBER_MWS "mwses"
#define CALIBER_ARROW "arrows"
#define CALIBER_FUEL "flamer fuel"
#define CALIBER_FOAM "foam darts"
#define CALIBER_ANY "anything even remotely ammolike"
