/*ALL DEFINES RELATED TO COMBAT GO HERE*/

//Damage and status effect defines

//Damage defines //TODO: merge these down to reduce on defines
#define BRUTE		"brute"
#define BURN		"fire"
#define TOX			"tox"
#define OXY			"oxy"
#define CLONE		"clone"
#define STAMINA 	"stamina"
#define BRAIN		"brain"

//bitflag damage defines. Used to be used for something else, but that use was removed cus it suckd
#define BRUTELOSS 		(1<<0)
#define FIRELOSS 		(1<<1)
#define TOXLOSS 		(1<<2)
#define OXYLOSS 		(1<<3)
#define RADIATIONLOSS	(1<<6)
#define CLONELOSS		(1<<7)
#define EMPLOSS			(1<<8)

#define DAMAGES_LIST list(BRUTELOSS, FIRELOSS, TOXLOSS, OXYLOSS, RADIATIONLOSS, CLONELOSS, EMPLOSS)

#define EFFECT_STUN		"stun"
#define EFFECT_KNOCKDOWN		"knockdown"
#define EFFECT_UNCONSCIOUS	"unconscious"
#define EFFECT_IRRADIATE	"irradiate"
#define EFFECT_STUTTER		"stutter"
#define EFFECT_SLUR 		"slur"
#define EFFECT_EYE_BLUR	"eye_blur"
#define EFFECT_DROWSY		"drowsy"
#define EFFECT_JITTER		"jitter"

// mob/living/var/combat_flags variable.
/// Default combat flags for those affected by sprinting (combat mode has been made into its own component)
#define COMBAT_FLAGS_DEFAULT				(COMBAT_FLAG_PARRY_CAPABLE | COMBAT_FLAG_BLOCK_CAPABLE)
/// Default combat flags for everyone else (so literally everyone but humans).
#define COMBAT_FLAGS_SPRINT_EXEMPT			(COMBAT_FLAG_SPRINT_ACTIVE | COMBAT_FLAG_SPRINT_TOGGLED | COMBAT_FLAG_SPRINT_FORCED | COMBAT_FLAG_PARRY_CAPABLE | COMBAT_FLAG_BLOCK_CAPABLE)

/// The user wants sprint mode on
#define COMBAT_FLAG_SPRINT_TOGGLED			(1<<0)
/// Sprint is currently active
#define COMBAT_FLAG_SPRINT_ACTIVE			(1<<1)
/// Currently attempting to crawl under someone
#define COMBAT_FLAG_ATTEMPTING_CRAWL		(1<<2)
/// Currently stamcritted
#define COMBAT_FLAG_HARD_STAMCRIT			(1<<3)
/// Currently attempting to resist up from the ground
#define COMBAT_FLAG_RESISTING_REST			(1<<4)
/// Intentionally resting
#define COMBAT_FLAG_INTENTIONALLY_RESTING	(1<<5)
/// Currently stamcritted but not as violently
#define COMBAT_FLAG_SOFT_STAMCRIT			(1<<6)
/// Force sprint mode on at all times, overrides everything including sprint disable traits.
#define COMBAT_FLAG_SPRINT_FORCED			(1<<7)
/// This mob is capable of using the active parrying system.
#define COMBAT_FLAG_PARRY_CAPABLE			(1<<8)
/// This mob is capable of using the active blocking system.
#define COMBAT_FLAG_BLOCK_CAPABLE			(1<<9)
/// This mob is capable of unarmed parrying
#define COMBAT_FLAG_UNARMED_PARRY			(1<<10)
/// This mob is currently actively blocking
#define COMBAT_FLAG_ACTIVE_BLOCKING			(1<<11)
/// This mob is currently starting an active block
#define COMBAT_FLAG_ACTIVE_BLOCK_STARTING	(1<<12)

// Helpers for getting someone's stamcrit state. Cast to living.
#define NOT_STAMCRIT 0
#define SOFT_STAMCRIT 1
#define HARD_STAMCRIT 2

// Stamcrit check helpers
#define IS_STAMCRIT(mob)					(CHECK_STAMCRIT(mob) != NOT_STAMCRIT)
#define CHECK_STAMCRIT(mob)					((mob.combat_flags & COMBAT_FLAG_HARD_STAMCRIT)? HARD_STAMCRIT : ((mob.combat_flags & COMBAT_FLAG_SOFT_STAMCRIT)? SOFT_STAMCRIT : NOT_STAMCRIT))

//stamina stuff
///Threshold over which attacks start being hindered.
#define STAMINA_NEAR_SOFTCRIT				90
///softcrit for stamina damage. prevents standing up, some actions that cost stamina, etc, but doesn't force a rest or stop movement
#define STAMINA_SOFTCRIT					100
///sanity cap to prevent stamina actions (that are still performable) from sending you into crit.
#define STAMINA_NEAR_CRIT					130
///crit for stamina damage. forces a rest, and stops movement until stamina goes back to stamina softcrit
#define STAMINA_CRIT						140
///same as STAMINA_SOFTCRIT except for the more traditional health calculations
#define STAMINA_SOFTCRIT_TRADITIONAL		0
///ditto, but for STAMINA_CRIT
#define STAMINA_CRIT_TRADITIONAL			-40

#define CRAWLUNDER_DELAY							30 //Delay for crawling under a standing mob

//Bitflags defining which status effects could be or are inflicted on a mob
// This is a bit out of date/inaccurate in light of all the new status effects and is probably pending rework.
#define CANSTUN			(1<<0)
#define CANKNOCKDOWN	(1<<1)
#define CANUNCONSCIOUS	(1<<2)
#define CANPUSH			(1<<3)
#define GODMODE			(1<<4)
#define CANSTAGGER		(1<<5)

//Health Defines
#define HEALTH_THRESHOLD_CRIT 0
#define HEALTH_THRESHOLD_FULLCRIT -175
#define HEALTH_THRESHOLD_DEAD -200

#define CRIT_AGONY_THRESHOLD 0.1 // or about 20 damage into crit
#define CRIT_AGONY_THRESHOLD_LIGHT 0.2 // or about 40 damage into crit
#define CRIT_AGONY_THRESHOLD_MAJOR 0.6 // or about 120 damage into crit
#define CRIT_AGONY_THRESHOLD_CATASTROPHIC 0.85 // u die, maybe

#define CRIT_AGONY_NONE 0
#define CRIT_AGONY_LIGHT 1
#define CRIT_AGONY_MAJOR 2
#define CRIT_AGONY_CATASTROPHIC 3
#define CRIT_AGONY_DIED 4

//Actual combat defines

//click cooldowns, in tenths of a second, used for various combat actions
#define CLICK_CD_MELEE 8
#define CLICK_CD_RANGE 5
#define CLICK_CD_RAPID 2
#define CLICK_CD_CLICK_ABILITY 6
#define CLICK_CD_HANDCUFFED 10
#define CLICK_CD_RESIST 20
#define CLICK_CD_GRABBING 10

//Cuff resist speeds
#define FAST_CUFFBREAK 1
#define INSTANT_CUFFBREAK 2

//Grab levels
#define GRAB_PASSIVE				0
#define GRAB_AGGRESSIVE				1
#define GRAB_NECK					2
#define GRAB_KILL					3

//attack visual effects
#define ATTACK_EFFECT_PUNCH		"punch"
#define ATTACK_EFFECT_KICK		"kick"
#define ATTACK_EFFECT_SMASH		"smash"
#define ATTACK_EFFECT_CLAW		"claw"
#define ATTACK_EFFECT_DISARM	"disarm"
#define ATTACK_EFFECT_ASS_SLAP  "ass_slap"
#define ATTACK_EFFECT_FACE_SLAP "face_slap"
#define ATTACK_EFFECT_BITE		"bite"
#define ATTACK_EFFECT_MECHFIRE	"mech_fire"
#define ATTACK_EFFECT_MECHTOXIN	"mech_toxin"
#define ATTACK_EFFECT_BOOP		"boop" //Honk

//intent defines
#define INTENT_HELP   "help"
#define INTENT_GRAB   "grab"
#define INTENT_DISARM "disarm"
#define INTENT_HARM   "harm"
//NOTE: INTENT_HOTKEY_* defines are not actual intents!
//they are here to support hotkeys
#define INTENT_HOTKEY_LEFT  "left"
#define INTENT_HOTKEY_RIGHT "right"

//the define for visible message range in combat
#define COMBAT_MESSAGE_RANGE 3
#define DEFAULT_MESSAGE_RANGE 7

//Shove knockdown lengths (deciseconds)
#define SHOVE_KNOCKDOWN_SOLID 30
#define SHOVE_KNOCKDOWN_HUMAN 30
#define SHOVE_KNOCKDOWN_TABLE 30
#define SHOVE_KNOCKDOWN_COLLATERAL 10
/// how long they're staggered for
#define SHOVE_STAGGER_DURATION 35
/// how long they're off balance for
#define SHOVE_OFFBALANCE_DURATION 30
//Shove disarming item list
GLOBAL_LIST_INIT(shove_disarming_types, typecacheof(list(
	/obj/item/gun)))


//Embedded objects

#define EMBEDDED_PAIN_CHANCE 					15	//Chance for embedded objects to cause pain (damage user)
#define EMBEDDED_ITEM_FALLOUT 					5	//Chance for embedded object to fall out (causing pain but removing the object)
#define EMBED_CHANCE							45	//Chance for an object to embed into somebody when thrown (if it's sharp)
#define EMBEDDED_PAIN_MULTIPLIER				2	//Coefficient of multiplication for the damage the item does while embedded (this*item.w_class)
#define EMBEDDED_FALL_PAIN_MULTIPLIER			5	//Coefficient of multiplication for the damage the item does when it falls out (this*item.w_class)
#define EMBEDDED_IMPACT_PAIN_MULTIPLIER			4	//Coefficient of multiplication for the damage the item does when it first embeds (this*item.w_class)
#define EMBED_THROWSPEED_THRESHOLD				4	//The minimum value of an item's throw_speed for it to embed (Unless it has embedded_ignore_throwspeed_threshold set to 1)
#define EMBEDDED_UNSAFE_REMOVAL_PAIN_MULTIPLIER 8	//Coefficient of multiplication for the damage the item does when removed without a surgery (this*item.w_class)
#define EMBEDDED_UNSAFE_REMOVAL_TIME			30	//A Time in ticks, total removal time = (this*item.w_class)
#define EMBEDDED_JOSTLE_CHANCE					5	//Chance for embedded objects to cause pain every time they move (jostle)
#define EMBEDDED_JOSTLE_PAIN_MULTIPLIER			1	//Coefficient of multiplication for the damage the item does while
#define EMBEDDED_PAIN_STAM_PCT					0.0	//This percentage of all pain will be dealt as stam damage rather than brute (0-1)
#define EMBED_CHANCE_TURF_MOD					-15	//You are this many percentage points less likely to embed into a turf (good for things glass shards and spears vs walls)

#define EMBED_HARMLESS list("pain_mult" = 0, "jostle_pain_mult" = 0, "ignore_throwspeed_threshold" = TRUE)
#define EMBED_HARMLESS_SUPERIOR list("pain_mult" = 0, "jostle_pain_mult" = 0, "ignore_throwspeed_threshold" = TRUE, "embed_chance" = 100, "fall_chance" = 0.1)
#define EMBED_POINTY list("ignore_throwspeed_threshold" = TRUE)
#define EMBED_POINTY_SUPERIOR list("embed_chance" = 100, "ignore_throwspeed_threshold" = TRUE)

//Gun trigger guards
#define TRIGGER_GUARD_ALLOW_ALL -1
#define TRIGGER_GUARD_NONE 0
#define TRIGGER_GUARD_NORMAL 1
//E-gun self-recharge values
#define EGUN_NO_SELFCHARGE 0
#define EGUN_SELFCHARGE 1
#define EGUN_SELFCHARGE_BORG 2

//Gun suppression
#define SUPPRESSED_NONE 0
#define SUPPRESSED_QUIET 1 ///standard suppressed
#define SUPPRESSED_VERY 2 /// no message

//Nice shot bonus
#define NICE_SHOT_RICOCHET_BONUS	20	//if the shooter has the NICE_SHOT trait and they fire a ricocheting projectile, add this to the ricochet chance and auto aim angle

//Object/Item sharpness
#define SHARP_NONE			0
#define SHARP_EDGED			1
#define SHARP_POINTY		2

//His Grace.
#define HIS_GRACE_SATIATED 0 //He hungers not. If bloodthirst is set to this, His Grace is asleep.
#define HIS_GRACE_PECKISH 20 //Slightly hungry.
#define HIS_GRACE_HUNGRY 60 //Getting closer. Increases damage up to a minimum of 20.
#define HIS_GRACE_FAMISHED 100 //Dangerous. Increases damage up to a minimum of 25 and cannot be dropped.
#define HIS_GRACE_STARVING 120 //Incredibly close to breaking loose. Increases damage up to a minimum of 30.
#define HIS_GRACE_CONSUME_OWNER 140 //His Grace consumes His owner at this point and becomes aggressive.
#define HIS_GRACE_FALL_ASLEEP 160 //If it reaches this point, He falls asleep and resets.

#define HIS_GRACE_FORCE_BONUS 4 //How much force is gained per kill.

#define EXPLODE_NONE 0				//Don't even ask me why we need this.
#define EXPLODE_DEVASTATE 1
#define EXPLODE_HEAVY 2
#define EXPLODE_LIGHT 3
#define EXPLODE_GIB_THRESHOLD 50

#define GRENADE_CLUMSY_FUMBLE 1
#define GRENADE_NONCLUMSY_FUMBLE 2
#define GRENADE_NO_FUMBLE 3

#define BODY_ZONE_HEAD		"head"
#define BODY_ZONE_CHEST		"chest"
#define BODY_ZONE_L_ARM		"l_arm"
#define BODY_ZONE_R_ARM		"r_arm"
#define BODY_ZONE_L_LEG		"l_leg"
#define BODY_ZONE_R_LEG		"r_leg"

GLOBAL_LIST_INIT(main_body_parts, list(
	BODY_ZONE_HEAD,
	BODY_ZONE_CHEST,
	BODY_ZONE_L_ARM,
	BODY_ZONE_R_ARM,
	BODY_ZONE_L_LEG,
	BODY_ZONE_R_LEG
))
GLOBAL_LIST_INIT(main_body_parts2words, list(
	BODY_ZONE_HEAD = "head",
	BODY_ZONE_CHEST = "chest",
	BODY_ZONE_L_ARM = "left arm",
	BODY_ZONE_R_ARM = "right arm",
	BODY_ZONE_L_LEG = "left leg",
	BODY_ZONE_R_LEG = "right leg",
))

#define BODY_ZONE_PRECISE_EYES		"eyes"
#define BODY_ZONE_PRECISE_MOUTH		"mouth"
#define BODY_ZONE_PRECISE_GROIN		"groin"
#define BODY_ZONE_PRECISE_L_HAND	"l_hand"
#define BODY_ZONE_PRECISE_R_HAND	"r_hand"
#define BODY_ZONE_PRECISE_L_FOOT	"l_foot"
#define BODY_ZONE_PRECISE_R_FOOT	"r_foot"


//We will round to this value in damage calculations.
#define DAMAGE_PRECISION 0.01

//items total mass, used to calculate their attacks' stamina costs. If not defined, the cost will be (w_class * 1.25)
#define TOTAL_MASS_TINY_ITEM		1.25
#define TOTAL_MASS_SMALL_ITEM		2.5
#define TOTAL_MASS_NORMAL_ITEM		3.75
#define TOTAL_MASS_BULKY_ITEM		5
#define TOTAL_MASS_HUGE_ITEM		6.25
#define TOTAL_MASS_GIGANTIC_ITEM	7.5

#define TOTAL_MASS_HAND_REPLACEMENT	5 //standard punching stamina cost. most hand replacements are huge items anyway.
#define TOTAL_MASS_MEDIEVAL_WEAPON	15 //very, very generic average sword/warpick/etc. weight in pounds.
#define TOTAL_MASS_TOY_SWORD 1.5

//stamina cost defines.
#define STAM_COST_ATTACK_OBJ_MULT	1.2
#define STAM_COST_ATTACK_MOB_MULT	1
#define STAM_COST_BATON_MOB_MULT	1
#define STAM_COST_NO_COMBAT_MULT	1.25
#define STAM_COST_W_CLASS_MULT		1.25
#define STAM_COST_THROW_MULT		1
#define STAM_COST_THROW_MOB			2.5 //multiplied by (mob size + 1)^2.

///Multiplier of the (STAMINA_NEAR_CRIT - user current stamina loss) : (STAMINA_NEAR_CRIT - STAMINA_SOFTCRIT) ratio used in damage penalties when stam soft-critted.
#define STAM_CRIT_ITEM_ATTACK_PENALTY	0.66
/// changeNext_move penalty multiplier of the above.
#define STAM_CRIT_ITEM_ATTACK_DELAY		1.75
/// Damage penalty when fighting prone.
#define LYING_DAMAGE_PENALTY			0.7
/// Added delay when firing guns stam-softcritted. Summed with a hardset CLICK_CD_RANGE delay, similar to STAM_CRIT_DAMAGE_DELAY otherwise.
#define STAM_CRIT_GUN_DELAY			2.75

//stamina recovery defines. Blocked if combat mode is on.
#define STAM_RECOVERY_STAM_CRIT		-7.5
#define STAM_RECOVERY_RESTING		-6
#define STAM_RECOVERY_NORMAL		-3
#define STAM_RECOVERY_LIMB			4 //limbs recover stamina separately from handle_status_effects(), and aren't blocked by combat mode.

/**
 * should the current-attack-damage be lower than the item force multiplied by this value,
 * a "inefficiently" prefix will be added to the message.
 */
#define FEEBLE_ATTACK_MSG_THRESHOLD 0.5

/*
 * faction defines
 */
// TODO: make this work
/* #define FACTION_HOSTILE "hostile"
#define FACTION_DEATHCLAW "deathclaw"
#define FACTION_GECKO "gecko"
#define FACTION_RAT "rat"
#define FACTION_YAOGUAI "yaoguai"
#define FACTION_NIGHTSTALKER "nightstalker"
#define FACTION_ANT "ant"
#define FACTION_CAZADOR "cazador"
#define FACTION_RADSCORPION "radscorpion"
#define FACTION_SUPERMUTANT "supermutant"
#define FACTION_WASTEBOT "wastebot"
#define FACTION_CHINESE "china"
#define FACTION_RAIDER "raider"
#define FACTION_CARP "carp"
#define FACTION_NEUTRAL "neutral"
#define FACTION_DOG "dog"
#define FACTION_WOLF "wolf"
#define FACTION_PIRATE "pirate"
#define FACTION_SILICON "silicon"
#define FACTION_PLANTS "plants"
#define FACTION_TURRET "turret"
#define FACTION_ENCLAVE "enclave"
#define FACTION_GHOUL "ghoul"
#define FACTION_SLIME "slime"
#define FACTION_SKELETON "skeleton"
#define FACTION_BIGHORNER "bighorner"
 */
/// Supereffective typegroups
/// ALL simplemobs
#define SE_ALL_SIMPLEMOBS (1<<0)
/// All simple_animal/hostile
#define SE_HOSTILE_SIMPLEMOBS (1<<1)
/// All animal-like critters
#define SE_ANIMALS (1<<2)
/// All robot-like critters
#define SE_ROBOTS (1<<3)
/// All human-like critters (not players)
#define SE_HUMANLIKE (1<<4)
/// All insect-like critters
#define SE_INSECTS (1<<5)
/// Anything with a ckey (characters, mobs, etc)
#define SE_PLAYERS (1<<6)
/// Ignore critters that have been lazarused
#define SE_NO_LAZARUS (1<<7)

/* * * * * * * * * *
 * Bullet defines! *
 * * * * * * * * * */

/// Bullet speed defines
#define BULLET_SPEED_BASE (TILES_TO_PIXELS(30)) //960 (30 tiles per second, 32 pixels per tile)

/// Arrow speed defines
#define ARROW_SPEED_BASE (BULLET_SPEED_BASE / 3)

/// Bullet damage modifier defines
#define BULLET_MATCH_MULT_DAMAGE 1.25 // rare, pack a punch
#define BULLET_SURPLUS_MULT_DAMAGE 1 // standard ammo from an ammobench
#define BULLET_HANDLOAD_MULT_DAMAGE 0.75 // trash ammo you can make anywhere with a reloader tool, most common

/// Bullet speed modifier defines
#define BULLET_MATCH_MULT_SPEED 2
#define BULLET_SURPLUS_MULT_SPEED 1
#define BULLET_HANDLOAD_MULT_SPEED 0.75

/// Bullet wounding modifier defines
#define BULLET_MATCH_MULT_WOUND 1.25
#define BULLET_SURPLUS_MULT_WOUND 1
#define BULLET_HANDLOAD_MULT_WOUND 0.75

/// Bullet recoil modifier defines
#define BULLET_MATCH_MULT_RECOIL 2
#define BULLET_SURPLUS_MULT_RECOIL 1
#define BULLET_HANDLOAD_MULT_RECOIL 0.5

/// Rubber bullet lethal damage multiplier
#define RUBBERY_DAMAGE_MULT 0.1

/// Rubber bullet recoil multiplier
#define RUBBERY_RECOIL_MULT 0.5

/// Bullet Recoil defines
#define BULLET_RECOIL_BASE (2)
#define BULLET_RECOIL_PISTOL_SMALL (BULLET_RECOIL_BASE * 1)
#define BULLET_RECOIL_PISTOL_MEDIUM (BULLET_RECOIL_BASE * 1)
#define BULLET_RECOIL_PISTOL_LARGE (BULLET_RECOIL_BASE * 2)
#define BULLET_RECOIL_RIFLE_SMALL (BULLET_RECOIL_BASE * 1.5)
#define BULLET_RECOIL_RIFLE_MEDIUM (BULLET_RECOIL_BASE * 3)
#define BULLET_RECOIL_RIFLE_LARGE (BULLET_RECOIL_BASE * 25)
#define BULLET_RECOIL_SHOTGUN (BULLET_RECOIL_BASE * 2)
#define BULLET_RECOIL_GAUSS (BULLET_RECOIL_BASE * 25)
#define BULLET_RECOIL_LASER (BULLET_RECOIL_BASE * 1)
#define BULLET_RECOIL_HEAVY_LASER (BULLET_RECOIL_BASE * 3)
#define BULLET_RECOIL_PLASMA (BULLET_RECOIL_BASE * 5)


/// Bullet damage defines
/// .22 LR
#define BULLET_DAMAGE_PISTOL_22 15
#define BULLET_DAMAGE_PISTOL_22_HANDLOAD (BULLET_DAMAGE_PISTOL_22 * BULLET_HANDLOAD_MULT_DAMAGE)
#define BULLET_DAMAGE_PISTOL_22_MATCH (BULLET_DAMAGE_PISTOL_22 * BULLET_MATCH_MULT_DAMAGE)
#define BULLET_STAMINA_PISTOL_22 (BULLET_DAMAGE_PISTOL_22 * 0.5)
#define BULLET_RECOIL_PISTOL_22 BULLET_RECOIL_PISTOL_SMALL
#define BULLET_RECOIL_PISTOL_22_HANDLOAD (BULLET_RECOIL_PISTOL_22 * BULLET_HANDLOAD_MULT_RECOIL)
#define BULLET_RECOIL_PISTOL_22_MATCH (BULLET_RECOIL_PISTOL_22 * BULLET_MATCH_MULT_RECOIL)
#define BULLET_SPEED_PISTOL_22 (BULLET_SPEED_BASE * 0.85 * 2)
#define BULLET_SPEED_PISTOL_22_HANDLOAD (BULLET_SPEED_PISTOL_22 * BULLET_HANDLOAD_MULT_SPEED)
#define BULLET_SPEED_PISTOL_22_MATCH (BULLET_SPEED_PISTOL_22 * BULLET_MATCH_MULT_SPEED)
#define BULLET_WOUND_PISTOL_22 1
#define BULLET_WOUND_PISTOL_22_HANDLOAD (BULLET_WOUND_PISTOL_22 * BULLET_HANDLOAD_MULT_WOUND)
#define BULLET_WOUND_PISTOL_22_MATCH (BULLET_WOUND_PISTOL_22 * BULLET_MATCH_MULT_WOUND)
#define BULLET_WOUND_PISTOL_22_NAKED_MULT 1
#define RUBBERY_DAMAGE_PISTOL_22 (BULLET_DAMAGE_PISTOL_22 * RUBBERY_DAMAGE_MULT)
#define RUBBERY_STAMINA_PISTOL_22 (BULLET_DAMAGE_PISTOL_22)
#define RUBBERY_RECOIL_PISTOL_22 (BULLET_RECOIL_PISTOL_22 * RUBBERY_RECOIL_MULT)
#define RUBBERY_WOUND_PISTOL_22 (BULLET_WOUND_PISTOL_22 * 2)

#define BULLET_DAMAGE_PISTOL_9MM 25
#define BULLET_DAMAGE_PISTOL_9MM_HANDLOAD (BULLET_DAMAGE_PISTOL_9MM * BULLET_HANDLOAD_MULT_DAMAGE)
#define BULLET_DAMAGE_PISTOL_9MM_MATCH (BULLET_DAMAGE_PISTOL_9MM * BULLET_MATCH_MULT_DAMAGE)
#define BULLET_STAMINA_PISTOL_9MM (BULLET_DAMAGE_PISTOL_9MM * 0.5)
#define BULLET_RECOIL_PISTOL_9MM BULLET_RECOIL_PISTOL_SMALL
#define BULLET_RECOIL_PISTOL_9MM_HANDLOAD (BULLET_RECOIL_PISTOL_9MM * BULLET_HANDLOAD_MULT_RECOIL)
#define BULLET_RECOIL_PISTOL_9MM_MATCH (BULLET_RECOIL_PISTOL_9MM * BULLET_MATCH_MULT_RECOIL)
#define BULLET_SPEED_PISTOL_9MM (BULLET_SPEED_BASE * 0.85)
#define BULLET_SPEED_PISTOL_9MM_HANDLOAD (BULLET_SPEED_PISTOL_9MM * BULLET_HANDLOAD_MULT_SPEED)
#define BULLET_SPEED_PISTOL_9MM_MATCH (BULLET_SPEED_PISTOL_9MM * BULLET_MATCH_MULT_SPEED)
#define BULLET_WOUND_PISTOL_9MM 5
#define BULLET_WOUND_PISTOL_9MM_HANDLOAD (BULLET_WOUND_PISTOL_9MM * BULLET_HANDLOAD_MULT_WOUND)
#define BULLET_WOUND_PISTOL_9MM_MATCH (BULLET_WOUND_PISTOL_9MM * BULLET_MATCH_MULT_WOUND)
#define BULLET_WOUND_PISTOL_9MM_NAKED_MULT 1
#define RUBBERY_DAMAGE_PISTOL_9MM (BULLET_DAMAGE_PISTOL_9MM * RUBBERY_DAMAGE_MULT)
#define RUBBERY_STAMINA_PISTOL_9MM (BULLET_DAMAGE_PISTOL_9MM)
#define RUBBERY_RECOIL_PISTOL_9MM (BULLET_RECOIL_PISTOL_9MM * RUBBERY_RECOIL_MULT)
#define RUBBERY_WOUND_PISTOL_9MM (BULLET_WOUND_PISTOL_9MM * 2)

#define BULLET_DAMAGE_PISTOL_45ACP 36
#define BULLET_DAMAGE_PISTOL_45ACP_HANDLOAD (BULLET_DAMAGE_PISTOL_45ACP * BULLET_HANDLOAD_MULT_DAMAGE)
#define BULLET_DAMAGE_PISTOL_45ACP_MATCH (BULLET_DAMAGE_PISTOL_45ACP * BULLET_MATCH_MULT_DAMAGE)
#define BULLET_STAMINA_PISTOL_45ACP (BULLET_DAMAGE_PISTOL_45ACP * 0.5)
#define BULLET_RECOIL_PISTOL_45ACP BULLET_RECOIL_PISTOL_MEDIUM
#define BULLET_RECOIL_PISTOL_45ACP_HANDLOAD (BULLET_RECOIL_PISTOL_45ACP * BULLET_HANDLOAD_MULT_RECOIL)
#define BULLET_RECOIL_PISTOL_45ACP_MATCH (BULLET_RECOIL_PISTOL_45ACP * BULLET_MATCH_MULT_RECOIL)
#define BULLET_SPEED_PISTOL_45ACP (BULLET_SPEED_BASE * 0.90)
#define BULLET_SPEED_PISTOL_45ACP_HANDLOAD (BULLET_SPEED_PISTOL_45ACP * BULLET_HANDLOAD_MULT_SPEED)
#define BULLET_SPEED_PISTOL_45ACP_MATCH (BULLET_SPEED_PISTOL_45ACP * BULLET_MATCH_MULT_SPEED)
#define BULLET_WOUND_PISTOL_45ACP 5
#define BULLET_WOUND_PISTOL_45ACP_HANDLOAD (BULLET_WOUND_PISTOL_45ACP * BULLET_HANDLOAD_MULT_WOUND)
#define BULLET_WOUND_PISTOL_45ACP_MATCH (BULLET_WOUND_PISTOL_45ACP * BULLET_MATCH_MULT_WOUND)
#define BULLET_WOUND_PISTOL_45ACP_NAKED_MULT 1
#define RUBBERY_DAMAGE_PISTOL_45ACP (BULLET_DAMAGE_PISTOL_45ACP * RUBBERY_DAMAGE_MULT)
#define RUBBERY_STAMINA_PISTOL_45ACP (BULLET_DAMAGE_PISTOL_45ACP)
#define RUBBERY_RECOIL_PISTOL_45ACP (BULLET_RECOIL_PISTOL_45ACP * RUBBERY_RECOIL_MULT)
#define RUBBERY_WOUND_PISTOL_45ACP (BULLET_WOUND_PISTOL_45ACP * 2)

#define BULLET_DAMAGE_PISTOL_10MM 30
#define BULLET_DAMAGE_PISTOL_10MM_HANDLOAD (BULLET_DAMAGE_PISTOL_10MM * BULLET_HANDLOAD_MULT_DAMAGE)
#define BULLET_DAMAGE_PISTOL_10MM_MATCH (BULLET_DAMAGE_PISTOL_10MM * BULLET_MATCH_MULT_DAMAGE)
#define BULLET_STAMINA_PISTOL_10MM (BULLET_DAMAGE_PISTOL_10MM * 0.5)
#define BULLET_RECOIL_PISTOL_10MM BULLET_RECOIL_PISTOL_MEDIUM
#define BULLET_RECOIL_PISTOL_10MM_HANDLOAD (BULLET_RECOIL_PISTOL_10MM * BULLET_HANDLOAD_MULT_RECOIL)
#define BULLET_RECOIL_PISTOL_10MM_MATCH (BULLET_RECOIL_PISTOL_10MM * BULLET_MATCH_MULT_RECOIL)
#define BULLET_SPEED_PISTOL_10MM (BULLET_SPEED_BASE * 0.90)
#define BULLET_SPEED_PISTOL_10MM_HANDLOAD (BULLET_SPEED_PISTOL_10MM * BULLET_HANDLOAD_MULT_SPEED)
#define BULLET_SPEED_PISTOL_10MM_MATCH (BULLET_SPEED_PISTOL_10MM * BULLET_MATCH_MULT_SPEED)
#define BULLET_WOUND_PISTOL_10MM 5
#define BULLET_WOUND_PISTOL_10MM_HANDLOAD (BULLET_WOUND_PISTOL_10MM * BULLET_HANDLOAD_MULT_WOUND)
#define BULLET_WOUND_PISTOL_10MM_MATCH (BULLET_WOUND_PISTOL_10MM * BULLET_MATCH_MULT_WOUND)
#define BULLET_WOUND_PISTOL_10MM_NAKED_MULT 1
#define RUBBERY_DAMAGE_PISTOL_10MM (BULLET_DAMAGE_PISTOL_10MM * RUBBERY_DAMAGE_MULT)
#define RUBBERY_STAMINA_PISTOL_10MM (BULLET_DAMAGE_PISTOL_10MM)
#define RUBBERY_RECOIL_PISTOL_10MM (BULLET_RECOIL_PISTOL_10MM * RUBBERY_RECOIL_MULT)
#define RUBBERY_WOUND_PISTOL_10MM (BULLET_WOUND_PISTOL_10MM * 2)

#define BULLET_DAMAGE_PISTOL_NEEDLE 16
#define BULLET_DAMAGE_PISTOL_NEEDLE_HANDLOAD (BULLET_DAMAGE_PISTOL_NEEDLE * BULLET_HANDLOAD_MULT_DAMAGE)
#define BULLET_DAMAGE_PISTOL_NEEDLE_MATCH (BULLET_DAMAGE_PISTOL_NEEDLE * BULLET_MATCH_MULT_DAMAGE)
#define BULLET_STAMINA_PISTOL_NEEDLE (BULLET_DAMAGE_PISTOL_NEEDLE * 0.5)
#define BULLET_RECOIL_PISTOL_NEEDLE BULLET_RECOIL_PISTOL_MEDIUM
#define BULLET_RECOIL_PISTOL_NEEDLE_HANDLOAD (BULLET_RECOIL_PISTOL_NEEDLE * BULLET_HANDLOAD_MULT_RECOIL)
#define BULLET_RECOIL_PISTOL_NEEDLE_MATCH (BULLET_RECOIL_PISTOL_NEEDLE * BULLET_MATCH_MULT_RECOIL)
#define BULLET_SPEED_PISTOL_NEEDLE (BULLET_SPEED_BASE * 0.90 * 1.5)
#define BULLET_SPEED_PISTOL_NEEDLE_HANDLOAD (BULLET_SPEED_PISTOL_NEEDLE * BULLET_HANDLOAD_MULT_SPEED)
#define BULLET_SPEED_PISTOL_NEEDLE_MATCH (BULLET_SPEED_PISTOL_NEEDLE * BULLET_MATCH_MULT_SPEED)
#define BULLET_WOUND_PISTOL_NEEDLE 30
#define BULLET_WOUND_PISTOL_NEEDLE_HANDLOAD (BULLET_WOUND_PISTOL_NEEDLE * BULLET_HANDLOAD_MULT_WOUND)
#define BULLET_WOUND_PISTOL_NEEDLE_MATCH (BULLET_WOUND_PISTOL_NEEDLE * BULLET_MATCH_MULT_WOUND)
#define BULLET_WOUND_PISTOL_NEEDLE_NAKED_MULT 10
#define RUBBERY_DAMAGE_PISTOL_NEEDLE (BULLET_DAMAGE_PISTOL_NEEDLE * RUBBERY_DAMAGE_MULT)
#define RUBBERY_STAMINA_PISTOL_NEEDLE (BULLET_DAMAGE_PISTOL_NEEDLE)
#define RUBBERY_RECOIL_PISTOL_NEEDLE (BULLET_RECOIL_PISTOL_NEEDLE * RUBBERY_RECOIL_MULT)
#define RUBBERY_WOUND_PISTOL_NEEDLE (BULLET_WOUND_PISTOL_NEEDLE * 20)

#define BULLET_DAMAGE_PISTOL_38 36
#define BULLET_DAMAGE_PISTOL_38_HANDLOAD (BULLET_DAMAGE_PISTOL_38 * BULLET_HANDLOAD_MULT_DAMAGE)
#define BULLET_DAMAGE_PISTOL_38_MATCH (BULLET_DAMAGE_PISTOL_38 * BULLET_MATCH_MULT_DAMAGE)
#define BULLET_STAMINA_PISTOL_38 (BULLET_DAMAGE_PISTOL_38 * 0.5)
#define BULLET_RECOIL_PISTOL_38 BULLET_RECOIL_PISTOL_MEDIUM
#define BULLET_RECOIL_PISTOL_38_HANDLOAD (BULLET_RECOIL_PISTOL_38 * BULLET_HANDLOAD_MULT_RECOIL)
#define BULLET_RECOIL_PISTOL_38_MATCH (BULLET_RECOIL_PISTOL_38 * BULLET_MATCH_MULT_RECOIL)
#define BULLET_SPEED_PISTOL_38 (BULLET_SPEED_BASE * 0.90)
#define BULLET_SPEED_PISTOL_38_HANDLOAD (BULLET_SPEED_PISTOL_38 * BULLET_HANDLOAD_MULT_SPEED)
#define BULLET_SPEED_PISTOL_38_MATCH (BULLET_SPEED_PISTOL_38 * BULLET_MATCH_MULT_SPEED)
#define BULLET_WOUND_PISTOL_38 5
#define BULLET_WOUND_PISTOL_38_HANDLOAD (BULLET_WOUND_PISTOL_38 * BULLET_HANDLOAD_MULT_WOUND)
#define BULLET_WOUND_PISTOL_38_MATCH (BULLET_WOUND_PISTOL_38 * BULLET_MATCH_MULT_WOUND)
#define BULLET_WOUND_PISTOL_38_NAKED_MULT 1
#define RUBBERY_DAMAGE_PISTOL_38 (BULLET_DAMAGE_PISTOL_38 * RUBBERY_DAMAGE_MULT)
#define RUBBERY_STAMINA_PISTOL_38 (BULLET_DAMAGE_PISTOL_38)
#define RUBBERY_RECOIL_PISTOL_38 (BULLET_RECOIL_PISTOL_38 * RUBBERY_RECOIL_MULT)
#define RUBBERY_WOUND_PISTOL_38 (BULLET_WOUND_PISTOL_38 * 2)

#define BULLET_DAMAGE_PISTOL_44 45
#define BULLET_DAMAGE_PISTOL_44_HANDLOAD (BULLET_DAMAGE_PISTOL_44 * BULLET_HANDLOAD_MULT_DAMAGE)
#define BULLET_DAMAGE_PISTOL_44_MATCH (BULLET_DAMAGE_PISTOL_44 * BULLET_MATCH_MULT_DAMAGE)
#define BULLET_STAMINA_PISTOL_44 (BULLET_DAMAGE_PISTOL_44 * 0.5)
#define BULLET_RECOIL_PISTOL_44 BULLET_RECOIL_PISTOL_LARGE
#define BULLET_RECOIL_PISTOL_44_HANDLOAD (BULLET_RECOIL_PISTOL_44 * BULLET_HANDLOAD_MULT_RECOIL)
#define BULLET_RECOIL_PISTOL_44_MATCH (BULLET_RECOIL_PISTOL_44 * BULLET_MATCH_MULT_RECOIL)
#define BULLET_SPEED_PISTOL_44 (BULLET_SPEED_BASE * 0.90)
#define BULLET_SPEED_PISTOL_44_HANDLOAD (BULLET_SPEED_PISTOL_44 * BULLET_HANDLOAD_MULT_SPEED)
#define BULLET_SPEED_PISTOL_44_MATCH (BULLET_SPEED_PISTOL_44 * BULLET_MATCH_MULT_SPEED)
#define BULLET_WOUND_PISTOL_44 10
#define BULLET_WOUND_PISTOL_44_HANDLOAD (BULLET_WOUND_PISTOL_44 * BULLET_HANDLOAD_MULT_WOUND)
#define BULLET_WOUND_PISTOL_44_MATCH (BULLET_WOUND_PISTOL_44 * BULLET_MATCH_MULT_WOUND)
#define BULLET_WOUND_PISTOL_44_NAKED_MULT 1
#define RUBBERY_DAMAGE_PISTOL_44 (BULLET_DAMAGE_PISTOL_44 * RUBBERY_DAMAGE_MULT)
#define RUBBERY_STAMINA_PISTOL_44 (BULLET_DAMAGE_PISTOL_44)
#define RUBBERY_RECOIL_PISTOL_44 (BULLET_RECOIL_PISTOL_44 * RUBBERY_RECOIL_MULT)
#define RUBBERY_WOUND_PISTOL_44 (BULLET_WOUND_PISTOL_44 * 2)

#define BULLET_DAMAGE_PISTOL_14MM 50
#define BULLET_DAMAGE_PISTOL_14MM_HANDLOAD (BULLET_DAMAGE_PISTOL_14MM * BULLET_HANDLOAD_MULT_DAMAGE)
#define BULLET_DAMAGE_PISTOL_14MM_MATCH (BULLET_DAMAGE_PISTOL_14MM * BULLET_MATCH_MULT_DAMAGE)
#define BULLET_STAMINA_PISTOL_14MM (BULLET_DAMAGE_PISTOL_14MM * 0.5)
#define BULLET_RECOIL_PISTOL_14MM (BULLET_RECOIL_PISTOL_LARGE * 2)
#define BULLET_RECOIL_PISTOL_14MM_HANDLOAD (BULLET_RECOIL_PISTOL_14MM * BULLET_HANDLOAD_MULT_RECOIL)
#define BULLET_RECOIL_PISTOL_14MM_MATCH (BULLET_RECOIL_PISTOL_14MM * BULLET_MATCH_MULT_RECOIL)
#define BULLET_SPEED_PISTOL_14MM (BULLET_SPEED_BASE * 0.90)
#define BULLET_SPEED_PISTOL_14MM_HANDLOAD (BULLET_SPEED_PISTOL_14MM * BULLET_HANDLOAD_MULT_SPEED)
#define BULLET_SPEED_PISTOL_14MM_MATCH (BULLET_SPEED_PISTOL_14MM * BULLET_MATCH_MULT_SPEED)
#define BULLET_WOUND_PISTOL_14MM 10
#define BULLET_WOUND_PISTOL_14MM_HANDLOAD (BULLET_WOUND_PISTOL_14MM * BULLET_HANDLOAD_MULT_WOUND)
#define BULLET_WOUND_PISTOL_14MM_MATCH (BULLET_WOUND_PISTOL_14MM * BULLET_MATCH_MULT_WOUND)
#define BULLET_WOUND_PISTOL_14MM_NAKED_MULT 1
#define RUBBERY_DAMAGE_PISTOL_14MM (BULLET_DAMAGE_PISTOL_14MM * RUBBERY_DAMAGE_MULT)
#define RUBBERY_STAMINA_PISTOL_14MM (BULLET_DAMAGE_PISTOL_14MM)
#define RUBBERY_RECOIL_PISTOL_14MM (BULLET_RECOIL_PISTOL_14MM * RUBBERY_RECOIL_MULT)
#define RUBBERY_WOUND_PISTOL_14MM (BULLET_WOUND_PISTOL_14MM * 2)

#define BULLET_DAMAGE_RIFLE_223 36
#define BULLET_DAMAGE_RIFLE_223_HANDLOAD (BULLET_DAMAGE_RIFLE_223 * BULLET_HANDLOAD_MULT_DAMAGE)
#define BULLET_DAMAGE_RIFLE_223_MATCH (BULLET_DAMAGE_RIFLE_223 * BULLET_MATCH_MULT_DAMAGE)
#define BULLET_STAMINA_RIFLE_223 (BULLET_DAMAGE_RIFLE_223 * 0.2)
#define BULLET_RECOIL_RIFLE_223 BULLET_RECOIL_RIFLE_SMALL
#define BULLET_RECOIL_RIFLE_223_HANDLOAD (BULLET_RECOIL_RIFLE_223 * BULLET_HANDLOAD_MULT_RECOIL)
#define BULLET_RECOIL_RIFLE_223_MATCH (BULLET_RECOIL_RIFLE_223 * BULLET_MATCH_MULT_RECOIL)
#define BULLET_SPEED_RIFLE_223 (BULLET_SPEED_BASE * 1.2)
#define BULLET_SPEED_RIFLE_223_HANDLOAD (BULLET_SPEED_RIFLE_223 * BULLET_HANDLOAD_MULT_SPEED)
#define BULLET_SPEED_RIFLE_223_MATCH (BULLET_SPEED_RIFLE_223 * BULLET_MATCH_MULT_SPEED)
#define BULLET_WOUND_RIFLE_223 5
#define BULLET_WOUND_RIFLE_223_HANDLOAD (BULLET_WOUND_RIFLE_223 * BULLET_HANDLOAD_MULT_WOUND)
#define BULLET_WOUND_RIFLE_223_MATCH (BULLET_WOUND_RIFLE_223 * BULLET_MATCH_MULT_WOUND)
#define BULLET_WOUND_RIFLE_223_NAKED_MULT 1
#define RUBBERY_DAMAGE_RIFLE_223 (BULLET_DAMAGE_RIFLE_223 * RUBBERY_DAMAGE_MULT)
#define RUBBERY_STAMINA_RIFLE_223 (BULLET_DAMAGE_RIFLE_223)
#define RUBBERY_RECOIL_RIFLE_223 (BULLET_RECOIL_RIFLE_223 * RUBBERY_RECOIL_MULT)
#define RUBBERY_WOUND_RIFLE_223 (BULLET_WOUND_RIFLE_223 * 2)

#define BULLET_DAMAGE_RIFLE_5MM 30
#define BULLET_DAMAGE_RIFLE_5MM_HANDLOAD (BULLET_DAMAGE_RIFLE_5MM * BULLET_HANDLOAD_MULT_DAMAGE)
#define BULLET_DAMAGE_RIFLE_5MM_MATCH (BULLET_DAMAGE_RIFLE_5MM * BULLET_MATCH_MULT_DAMAGE)
#define BULLET_STAMINA_RIFLE_5MM (BULLET_DAMAGE_RIFLE_5MM * 0.2)
#define BULLET_RECOIL_RIFLE_5MM BULLET_RECOIL_RIFLE_SMALL
#define BULLET_RECOIL_RIFLE_5MM_HANDLOAD (BULLET_RECOIL_RIFLE_5MM * BULLET_HANDLOAD_MULT_RECOIL)
#define BULLET_RECOIL_RIFLE_5MM_MATCH (BULLET_RECOIL_RIFLE_5MM * BULLET_MATCH_MULT_RECOIL)
#define BULLET_SPEED_RIFLE_5MM (BULLET_SPEED_BASE * 1.2 * 1.5)
#define BULLET_SPEED_RIFLE_5MM_HANDLOAD (BULLET_SPEED_RIFLE_5MM * BULLET_HANDLOAD_MULT_SPEED)
#define BULLET_SPEED_RIFLE_5MM_MATCH (BULLET_SPEED_RIFLE_5MM * BULLET_MATCH_MULT_SPEED)
#define BULLET_WOUND_RIFLE_5MM 5
#define BULLET_WOUND_RIFLE_5MM_HANDLOAD (BULLET_WOUND_RIFLE_5MM * BULLET_HANDLOAD_MULT_WOUND)
#define BULLET_WOUND_RIFLE_5MM_MATCH (BULLET_WOUND_RIFLE_5MM * BULLET_MATCH_MULT_WOUND)
#define BULLET_WOUND_RIFLE_5MM_NAKED_MULT 1
#define RUBBERY_DAMAGE_RIFLE_5MM (BULLET_DAMAGE_RIFLE_5MM * RUBBERY_DAMAGE_MULT)
#define RUBBERY_STAMINA_RIFLE_5MM (BULLET_DAMAGE_RIFLE_5MM)
#define RUBBERY_RECOIL_RIFLE_5MM (BULLET_RECOIL_RIFLE_5MM * RUBBERY_RECOIL_MULT)
#define RUBBERY_WOUND_RIFLE_5MM (BULLET_WOUND_RIFLE_5MM * 2)

#define BULLET_DAMAGE_RIFLE_473 30
#define BULLET_DAMAGE_RIFLE_473_HANDLOAD (BULLET_DAMAGE_RIFLE_473 * BULLET_HANDLOAD_MULT_DAMAGE)
#define BULLET_DAMAGE_RIFLE_473_MATCH (BULLET_DAMAGE_RIFLE_473 * BULLET_MATCH_MULT_DAMAGE)
#define BULLET_STAMINA_RIFLE_473 (BULLET_DAMAGE_RIFLE_473 * 0.2)
#define BULLET_RECOIL_RIFLE_473 BULLET_RECOIL_RIFLE_SMALL
#define BULLET_RECOIL_RIFLE_473_HANDLOAD (BULLET_RECOIL_RIFLE_473 * BULLET_HANDLOAD_MULT_RECOIL)
#define BULLET_RECOIL_RIFLE_473_MATCH (BULLET_RECOIL_RIFLE_473 * BULLET_MATCH_MULT_RECOIL)
#define BULLET_SPEED_RIFLE_473 (BULLET_SPEED_BASE * 1.2)
#define BULLET_SPEED_RIFLE_473_HANDLOAD (BULLET_SPEED_RIFLE_473 * BULLET_HANDLOAD_MULT_SPEED)
#define BULLET_SPEED_RIFLE_473_MATCH (BULLET_SPEED_RIFLE_473 * BULLET_MATCH_MULT_SPEED)
#define BULLET_WOUND_RIFLE_473 5
#define BULLET_WOUND_RIFLE_473_HANDLOAD (BULLET_WOUND_RIFLE_473 * BULLET_HANDLOAD_MULT_WOUND)
#define BULLET_WOUND_RIFLE_473_MATCH (BULLET_WOUND_RIFLE_473 * BULLET_MATCH_MULT_WOUND)
#define BULLET_WOUND_RIFLE_473_NAKED_MULT 1
#define RUBBERY_DAMAGE_RIFLE_473 (BULLET_DAMAGE_RIFLE_473 * RUBBERY_DAMAGE_MULT)
#define RUBBERY_STAMINA_RIFLE_473 (BULLET_DAMAGE_RIFLE_473)
#define RUBBERY_RECOIL_RIFLE_473 (BULLET_RECOIL_RIFLE_473 * RUBBERY_RECOIL_MULT)
#define RUBBERY_WOUND_RIFLE_473 (BULLET_WOUND_RIFLE_473 * 2)

#define BULLET_DAMAGE_RIFLE_308 45
#define BULLET_DAMAGE_RIFLE_308_HANDLOAD (BULLET_DAMAGE_RIFLE_308 * BULLET_HANDLOAD_MULT_DAMAGE)
#define BULLET_DAMAGE_RIFLE_308_MATCH (BULLET_DAMAGE_RIFLE_308 * BULLET_MATCH_MULT_DAMAGE)
#define BULLET_STAMINA_RIFLE_308 (BULLET_DAMAGE_RIFLE_308 * 0.5)
#define BULLET_RECOIL_RIFLE_308 BULLET_RECOIL_RIFLE_MEDIUM
#define BULLET_RECOIL_RIFLE_308_HANDLOAD (BULLET_RECOIL_RIFLE_308 * BULLET_HANDLOAD_MULT_RECOIL)
#define BULLET_RECOIL_RIFLE_308_MATCH (BULLET_RECOIL_RIFLE_308 * BULLET_MATCH_MULT_RECOIL)
#define BULLET_SPEED_RIFLE_308 (BULLET_SPEED_BASE * 2)
#define BULLET_SPEED_RIFLE_308_HANDLOAD (BULLET_SPEED_RIFLE_308 * BULLET_HANDLOAD_MULT_SPEED)
#define BULLET_SPEED_RIFLE_308_MATCH (BULLET_SPEED_RIFLE_308 * BULLET_MATCH_MULT_SPEED)
#define BULLET_WOUND_RIFLE_308 20
#define BULLET_WOUND_RIFLE_308_HANDLOAD (BULLET_WOUND_RIFLE_308 * BULLET_HANDLOAD_MULT_WOUND)
#define BULLET_WOUND_RIFLE_308_MATCH (BULLET_WOUND_RIFLE_308 * BULLET_MATCH_MULT_WOUND)
#define BULLET_WOUND_RIFLE_308_NAKED_MULT 1
#define RUBBERY_DAMAGE_RIFLE_308 (BULLET_DAMAGE_RIFLE_308 * RUBBERY_DAMAGE_MULT)
#define RUBBERY_STAMINA_RIFLE_308 (BULLET_DAMAGE_RIFLE_308)
#define RUBBERY_RECOIL_RIFLE_308 (BULLET_RECOIL_RIFLE_308 * RUBBERY_RECOIL_MULT)
#define RUBBERY_WOUND_RIFLE_308 (BULLET_WOUND_RIFLE_308 * 2)

#define BULLET_DAMAGE_RIFLE_4570 60
#define BULLET_DAMAGE_RIFLE_4570_HANDLOAD (BULLET_DAMAGE_RIFLE_4570 * BULLET_HANDLOAD_MULT_DAMAGE)
#define BULLET_DAMAGE_RIFLE_4570_MATCH (BULLET_DAMAGE_RIFLE_4570 * BULLET_MATCH_MULT_DAMAGE)
#define BULLET_STAMINA_RIFLE_4570 (BULLET_DAMAGE_RIFLE_4570 * 0.5)
#define BULLET_RECOIL_RIFLE_4570 (BULLET_RECOIL_RIFLE_LARGE * 0.85)
#define BULLET_RECOIL_RIFLE_4570_HANDLOAD (BULLET_RECOIL_RIFLE_4570 * BULLET_HANDLOAD_MULT_RECOIL)
#define BULLET_RECOIL_RIFLE_4570_MATCH (BULLET_RECOIL_RIFLE_4570 * BULLET_MATCH_MULT_RECOIL)
#define BULLET_SPEED_RIFLE_4570 (BULLET_SPEED_BASE * 2.5)
#define BULLET_SPEED_RIFLE_4570_HANDLOAD (BULLET_SPEED_RIFLE_4570 * BULLET_HANDLOAD_MULT_SPEED)
#define BULLET_SPEED_RIFLE_4570_MATCH (BULLET_SPEED_RIFLE_4570 * BULLET_MATCH_MULT_SPEED)
#define BULLET_WOUND_RIFLE_4570 25
#define BULLET_WOUND_RIFLE_4570_HANDLOAD (BULLET_WOUND_RIFLE_4570 * BULLET_HANDLOAD_MULT_WOUND)
#define BULLET_WOUND_RIFLE_4570_MATCH (BULLET_WOUND_RIFLE_4570 * BULLET_MATCH_MULT_WOUND)
#define BULLET_WOUND_RIFLE_4570_NAKED_MULT 1
#define RUBBERY_DAMAGE_RIFLE_4570 (BULLET_DAMAGE_RIFLE_4570 * RUBBERY_DAMAGE_MULT)
#define RUBBERY_STAMINA_RIFLE_4570 (BULLET_DAMAGE_RIFLE_4570)
#define RUBBERY_RECOIL_RIFLE_4570 (BULLET_RECOIL_RIFLE_4570 * RUBBERY_RECOIL_MULT)
#define RUBBERY_WOUND_RIFLE_4570 (BULLET_WOUND_RIFLE_4570 * 4)

#define BULLET_DAMAGE_RIFLE_3006 60
#define BULLET_DAMAGE_RIFLE_3006_HANDLOAD (BULLET_DAMAGE_RIFLE_3006 * BULLET_HANDLOAD_MULT_DAMAGE)
#define BULLET_DAMAGE_RIFLE_3006_MATCH (BULLET_DAMAGE_RIFLE_3006 * BULLET_MATCH_MULT_DAMAGE)
#define BULLET_STAMINA_RIFLE_3006 (BULLET_DAMAGE_RIFLE_3006 * 0.5)
#define BULLET_RECOIL_RIFLE_3006 BULLET_RECOIL_RIFLE_LARGE
#define BULLET_RECOIL_RIFLE_3006_HANDLOAD (BULLET_RECOIL_RIFLE_3006 * BULLET_HANDLOAD_MULT_RECOIL)
#define BULLET_RECOIL_RIFLE_3006_MATCH (BULLET_RECOIL_RIFLE_3006 * BULLET_MATCH_MULT_RECOIL)
#define BULLET_SPEED_RIFLE_3006 (BULLET_SPEED_BASE * 2.5)
#define BULLET_SPEED_RIFLE_3006_HANDLOAD (BULLET_SPEED_RIFLE_3006 * BULLET_HANDLOAD_MULT_SPEED)
#define BULLET_SPEED_RIFLE_3006_MATCH (BULLET_SPEED_RIFLE_3006 * BULLET_MATCH_MULT_SPEED)
#define BULLET_WOUND_RIFLE_3006 25
#define BULLET_WOUND_RIFLE_3006_HANDLOAD (BULLET_WOUND_RIFLE_3006 * BULLET_HANDLOAD_MULT_WOUND)
#define BULLET_WOUND_RIFLE_3006_MATCH (BULLET_WOUND_RIFLE_3006 * BULLET_MATCH_MULT_WOUND)
#define BULLET_WOUND_RIFLE_3006_NAKED_MULT 1
#define RUBBERY_DAMAGE_RIFLE_3006 (BULLET_DAMAGE_RIFLE_3006 * RUBBERY_DAMAGE_MULT)
#define RUBBERY_STAMINA_RIFLE_3006 (BULLET_DAMAGE_RIFLE_3006)
#define RUBBERY_RECOIL_RIFLE_3006 (BULLET_RECOIL_RIFLE_3006 * RUBBERY_RECOIL_MULT)
#define RUBBERY_WOUND_RIFLE_3006 (BULLET_WOUND_RIFLE_3006 * 4)

#define BULLET_DAMAGE_RIFLE_50MG 75
#define BULLET_DAMAGE_RIFLE_50MG_HANDLOAD (BULLET_DAMAGE_RIFLE_50MG * BULLET_HANDLOAD_MULT_DAMAGE)
#define BULLET_DAMAGE_RIFLE_50MG_MATCH (BULLET_DAMAGE_RIFLE_50MG * BULLET_MATCH_MULT_DAMAGE)
#define BULLET_STAMINA_RIFLE_50MG (BULLET_DAMAGE_RIFLE_50MG * 0.5)
#define BULLET_RECOIL_RIFLE_50MG (BULLET_RECOIL_RIFLE_LARGE * 2)
#define BULLET_RECOIL_RIFLE_50MG_HANDLOAD (BULLET_RECOIL_RIFLE_50MG * BULLET_HANDLOAD_MULT_RECOIL)
#define BULLET_RECOIL_RIFLE_50MG_MATCH (BULLET_RECOIL_RIFLE_50MG * BULLET_MATCH_MULT_RECOIL)
#define BULLET_SPEED_RIFLE_50MG (BULLET_SPEED_BASE * 3)
#define BULLET_SPEED_RIFLE_50MG_HANDLOAD (BULLET_SPEED_RIFLE_50MG * BULLET_HANDLOAD_MULT_SPEED)
#define BULLET_SPEED_RIFLE_50MG_MATCH (BULLET_SPEED_RIFLE_50MG * BULLET_MATCH_MULT_SPEED)
#define BULLET_WOUND_RIFLE_50MG 40
#define BULLET_WOUND_RIFLE_50MG_HANDLOAD (BULLET_WOUND_RIFLE_50MG * BULLET_HANDLOAD_MULT_WOUND)
#define BULLET_WOUND_RIFLE_50MG_MATCH (BULLET_WOUND_RIFLE_50MG * BULLET_MATCH_MULT_WOUND)
#define BULLET_WOUND_RIFLE_50MG_NAKED_MULT 1
#define RUBBERY_DAMAGE_RIFLE_50MG (BULLET_DAMAGE_RIFLE_50MG * RUBBERY_DAMAGE_MULT)
#define RUBBERY_STAMINA_RIFLE_50MG (BULLET_DAMAGE_RIFLE_50MG)
#define RUBBERY_RECOIL_RIFLE_50MG (BULLET_RECOIL_RIFLE_50MG * RUBBERY_RECOIL_MULT)
#define RUBBERY_WOUND_RIFLE_50MG (BULLET_WOUND_RIFLE_50MG * 2)

#define BULLET_DAMAGE_RIFLE_HEAVYNEEDLE 65

#define BULLET_DAMAGE_RIFLE_GAUSS 20
#define BULLET_DAMAGE_RIFLE_GAUSS_HANDLOAD (BULLET_DAMAGE_RIFLE_GAUSS * BULLET_HANDLOAD_MULT_DAMAGE)
#define BULLET_DAMAGE_RIFLE_GAUSS_MATCH (BULLET_DAMAGE_RIFLE_GAUSS * BULLET_MATCH_MULT_DAMAGE)
#define BULLET_STAMINA_RIFLE_GAUSS (BULLET_DAMAGE_RIFLE_GAUSS * 0.5)
#define BULLET_RECOIL_RIFLE_GAUSS BULLET_RECOIL_GAUSS
#define BULLET_RECOIL_RIFLE_GAUSS_HANDLOAD (BULLET_RECOIL_RIFLE_GAUSS * BULLET_HANDLOAD_MULT_RECOIL)
#define BULLET_RECOIL_RIFLE_GAUSS_MATCH (BULLET_RECOIL_RIFLE_GAUSS * BULLET_MATCH_MULT_RECOIL)
#define BULLET_SPEED_RIFLE_GAUSS (BULLET_SPEED_BASE * 5) // technically hitscan
#define BULLET_SPEED_RIFLE_GAUSS_HANDLOAD (BULLET_SPEED_RIFLE_GAUSS * BULLET_HANDLOAD_MULT_SPEED)
#define BULLET_SPEED_RIFLE_GAUSS_MATCH (BULLET_SPEED_RIFLE_GAUSS * BULLET_MATCH_MULT_SPEED)
#define BULLET_WOUND_RIFLE_GAUSS 25
#define BULLET_WOUND_RIFLE_GAUSS_HANDLOAD (BULLET_WOUND_RIFLE_GAUSS * BULLET_HANDLOAD_MULT_WOUND)
#define BULLET_WOUND_RIFLE_GAUSS_MATCH (BULLET_WOUND_RIFLE_GAUSS * BULLET_MATCH_MULT_WOUND)
#define BULLET_WOUND_RIFLE_GAUSS_NAKED_MULT 1
#define RUBBERY_DAMAGE_RIFLE_GAUSS (BULLET_DAMAGE_RIFLE_GAUSS * RUBBERY_DAMAGE_MULT)
#define RUBBERY_STAMINA_RIFLE_GAUSS (BULLET_DAMAGE_RIFLE_GAUSS)
#define RUBBERY_RECOIL_RIFLE_GAUSS (BULLET_RECOIL_RIFLE_GAUSS * RUBBERY_RECOIL_MULT)
#define RUBBERY_WOUND_RIFLE_GAUSS (BULLET_WOUND_RIFLE_GAUSS * 2)

#define BULLET_DAMAGE_SHOTGUN_PELLET 8
#define BULLET_DAMAGE_NEEDLER_PELLET 3 //will need revision when possible <-- Tox note
#define BULLET_DAMAGE_RATSHOT_PELLET 6 //six divides easily into the 36 damage of .357, and 60 damage of .45-70
#define BULLET_DAMAGE_SHOTGUN_PELLET_HANDLOAD (BULLET_DAMAGE_SHOTGUN_PELLET * BULLET_HANDLOAD_MULT_DAMAGE)
#define BULLET_DAMAGE_SHOTGUN_PELLET_MATCH (BULLET_DAMAGE_SHOTGUN_PELLET * BULLET_MATCH_MULT_DAMAGE)
#define BULLET_STAMINA_SHOTGUN_PELLET (BULLET_DAMAGE_SHOTGUN_PELLET * 0.1)
#define BULLET_RECOIL_SHOTGUN_PELLET BULLET_RECOIL_SHOTGUN
#define BULLET_RECOIL_SHOTGUN_PELLET_HANDLOAD (BULLET_RECOIL_SHOTGUN_PELLET * BULLET_HANDLOAD_MULT_RECOIL)
#define BULLET_RECOIL_SHOTGUN_PELLET_MATCH (BULLET_RECOIL_SHOTGUN_PELLET * BULLET_MATCH_MULT_RECOIL)
#define BULLET_SPEED_SHOTGUN_PELLET (BULLET_SPEED_BASE * 0.8)
#define BULLET_SPEED_SHOTGUN_PELLET_HANDLOAD (BULLET_SPEED_SHOTGUN_PELLET * BULLET_HANDLOAD_MULT_SPEED)
#define BULLET_SPEED_SHOTGUN_PELLET_MATCH (BULLET_SPEED_SHOTGUN_PELLET * BULLET_MATCH_MULT_SPEED)
#define BULLET_WOUND_SHOTGUN_PELLET 1
#define BULLET_WOUND_SHOTGUN_PELLET_HANDLOAD (BULLET_WOUND_SHOTGUN_PELLET * BULLET_HANDLOAD_MULT_WOUND)
#define BULLET_WOUND_SHOTGUN_PELLET_MATCH (BULLET_WOUND_SHOTGUN_PELLET * BULLET_MATCH_MULT_WOUND)
#define BULLET_WOUND_SHOTGUN_PELLET_NAKED_MULT 1
#define RUBBERY_DAMAGE_SHOTGUN_PELLET (BULLET_DAMAGE_SHOTGUN_PELLET * RUBBERY_DAMAGE_MULT)
#define RUBBERY_STAMINA_SHOTGUN_PELLET (BULLET_DAMAGE_SHOTGUN_PELLET * 1.5)
#define RUBBERY_RECOIL_SHOTGUN_PELLET (BULLET_RECOIL_SHOTGUN_PELLET * RUBBERY_RECOIL_MULT)
#define RUBBERY_WOUND_SHOTGUN_PELLET (BULLET_WOUND_SHOTGUN_PELLET * 2)

#define BULLET_DAMAGE_SHOTGUN_SLUG 60
#define BULLET_DAMAGE_SHOTGUN_SLUG_HANDLOAD (BULLET_DAMAGE_SHOTGUN_SLUG * BULLET_HANDLOAD_MULT_DAMAGE)
#define BULLET_DAMAGE_SHOTGUN_SLUG_MATCH (BULLET_DAMAGE_SHOTGUN_SLUG * BULLET_MATCH_MULT_DAMAGE)
#define BULLET_STAMINA_SHOTGUN_SLUG (BULLET_DAMAGE_SHOTGUN_SLUG * 0.5)
#define BULLET_RECOIL_SHOTGUN_SLUG BULLET_RECOIL_SHOTGUN
#define BULLET_RECOIL_SHOTGUN_SLUG_HANDLOAD (BULLET_RECOIL_SHOTGUN_SLUG * BULLET_HANDLOAD_MULT_RECOIL)
#define BULLET_RECOIL_SHOTGUN_SLUG_MATCH (BULLET_RECOIL_SHOTGUN_SLUG * BULLET_MATCH_MULT_RECOIL)
#define BULLET_SPEED_SHOTGUN_SLUG (BULLET_SPEED_BASE * 1.5)
#define BULLET_SPEED_SHOTGUN_SLUG_HANDLOAD (BULLET_SPEED_SHOTGUN_SLUG * BULLET_HANDLOAD_MULT_SPEED)
#define BULLET_SPEED_SHOTGUN_SLUG_MATCH (BULLET_SPEED_SHOTGUN_SLUG * BULLET_MATCH_MULT_SPEED)
#define BULLET_WOUND_SHOTGUN_SLUG 15
#define BULLET_WOUND_SHOTGUN_SLUG_HANDLOAD (BULLET_WOUND_SHOTGUN_SLUG * BULLET_HANDLOAD_MULT_WOUND)
#define BULLET_WOUND_SHOTGUN_SLUG_MATCH (BULLET_WOUND_SHOTGUN_SLUG * BULLET_MATCH_MULT_WOUND)
#define BULLET_WOUND_SHOTGUN_SLUG_NAKED_MULT 1
#define RUBBERY_DAMAGE_SHOTGUN_SLUG (BULLET_DAMAGE_SHOTGUN_SLUG * RUBBERY_DAMAGE_MULT)
#define RUBBERY_STAMINA_SHOTGUN_SLUG (BULLET_DAMAGE_SHOTGUN_SLUG)
#define RUBBERY_RECOIL_SHOTGUN_SLUG (BULLET_RECOIL_SHOTGUN_SLUG * RUBBERY_RECOIL_MULT)
#define RUBBERY_WOUND_SHOTGUN_SLUG (BULLET_WOUND_SHOTGUN_SLUG * 4)

#define BULLET_DAMAGE_SHOTGUN_TRAIN 25
#define BULLET_DAMAGE_SHOTGUN_TRAIN_HANDLOAD (BULLET_DAMAGE_SHOTGUN_TRAIN * BULLET_HANDLOAD_MULT_DAMAGE)
#define BULLET_DAMAGE_SHOTGUN_TRAIN_MATCH (BULLET_DAMAGE_SHOTGUN_TRAIN * BULLET_MATCH_MULT_DAMAGE)
#define BULLET_STAMINA_SHOTGUN_TRAIN (BULLET_DAMAGE_SHOTGUN_TRAIN * 0.5)
#define BULLET_RECOIL_SHOTGUN_TRAIN BULLET_RECOIL_SHOTGUN
#define BULLET_RECOIL_SHOTGUN_TRAIN_HANDLOAD (BULLET_RECOIL_SHOTGUN_TRAIN * BULLET_HANDLOAD_MULT_RECOIL)
#define BULLET_RECOIL_SHOTGUN_TRAIN_MATCH (BULLET_RECOIL_SHOTGUN_TRAIN * BULLET_MATCH_MULT_RECOIL)
#define BULLET_SPEED_SHOTGUN_TRAIN (BULLET_SPEED_BASE * 0.85)
#define BULLET_SPEED_SHOTGUN_TRAIN_HANDLOAD (BULLET_SPEED_SHOTGUN_TRAIN * BULLET_HANDLOAD_MULT_SPEED)
#define BULLET_SPEED_SHOTGUN_TRAIN_MATCH (BULLET_SPEED_SHOTGUN_TRAIN * BULLET_MATCH_MULT_SPEED)
#define BULLET_WOUND_SHOTGUN_TRAIN 25
#define BULLET_WOUND_SHOTGUN_TRAIN_HANDLOAD (BULLET_WOUND_SHOTGUN_TRAIN * BULLET_HANDLOAD_MULT_WOUND)
#define BULLET_WOUND_SHOTGUN_TRAIN_MATCH (BULLET_WOUND_SHOTGUN_TRAIN * BULLET_MATCH_MULT_WOUND)
#define BULLET_WOUND_SHOTGUN_TRAIN_NAKED_MULT 1
#define RUBBERY_DAMAGE_SHOTGUN_TRAIN (BULLET_DAMAGE_SHOTGUN_TRAIN * RUBBERY_DAMAGE_MULT)
#define RUBBERY_STAMINA_SHOTGUN_TRAIN (BULLET_DAMAGE_SHOTGUN_TRAIN)
#define RUBBERY_RECOIL_SHOTGUN_TRAIN (BULLET_RECOIL_SHOTGUN_TRAIN * RUBBERY_RECOIL_MULT)
#define RUBBERY_WOUND_SHOTGUN_TRAIN (BULLET_WOUND_SHOTGUN_TRAIN * 4)

#define BULLET_DAMAGE_FLINTLOCK 70
#define BULLET_DAMAGE_FLINTLOCK_HANDLOAD (BULLET_DAMAGE_FLINTLOCK * BULLET_HANDLOAD_MULT_DAMAGE)
#define BULLET_DAMAGE_FLINTLOCK_MATCH (BULLET_DAMAGE_FLINTLOCK * BULLET_MATCH_MULT_DAMAGE)
#define BULLET_STAMINA_FLINTLOCK (BULLET_DAMAGE_FLINTLOCK * 0.5)
#define BULLET_RECOIL_FLINTLOCK BULLET_RECOIL_SHOTGUN // not that it matters much
#define BULLET_RECOIL_FLINTLOCK_HANDLOAD (BULLET_RECOIL_FLINTLOCK * BULLET_HANDLOAD_MULT_RECOIL)
#define BULLET_RECOIL_FLINTLOCK_MATCH (BULLET_RECOIL_FLINTLOCK * BULLET_MATCH_MULT_RECOIL)
#define BULLET_SPEED_FLINTLOCK (BULLET_SPEED_BASE * 0.75)
#define BULLET_SPEED_FLINTLOCK_HANDLOAD (BULLET_SPEED_FLINTLOCK * BULLET_HANDLOAD_MULT_SPEED)
#define BULLET_SPEED_FLINTLOCK_MATCH (BULLET_SPEED_FLINTLOCK * BULLET_MATCH_MULT_SPEED)
#define BULLET_WOUND_FLINTLOCK 50
#define BULLET_WOUND_FLINTLOCK_HANDLOAD (BULLET_WOUND_FLINTLOCK * BULLET_HANDLOAD_MULT_WOUND)
#define BULLET_WOUND_FLINTLOCK_MATCH (BULLET_WOUND_FLINTLOCK * BULLET_MATCH_MULT_WOUND)
#define BULLET_WOUND_FLINTLOCK_NAKED_MULT 1
#define RUBBERY_DAMAGE_FLINTLOCK (BULLET_DAMAGE_FLINTLOCK * RUBBERY_DAMAGE_MULT)
#define RUBBERY_STAMINA_FLINTLOCK (BULLET_DAMAGE_FLINTLOCK)
#define RUBBERY_RECOIL_FLINTLOCK (BULLET_RECOIL_FLINTLOCK * RUBBERY_RECOIL_MULT)
#define RUBBERY_WOUND_FLINTLOCK (BULLET_WOUND_FLINTLOCK * 4)

#define BULLET_DAMAGE_GHOUL_ROCK 5
#define BULLET_DAMAGE_GHOUL_ROCK_HANDLOAD (BULLET_DAMAGE_GHOUL_ROCK * BULLET_HANDLOAD_MULT_DAMAGE)
#define BULLET_DAMAGE_GHOUL_ROCK_MATCH (BULLET_DAMAGE_GHOUL_ROCK * BULLET_MATCH_MULT_DAMAGE)
#define BULLET_STAMINA_GHOUL_ROCK (BULLET_DAMAGE_GHOUL_ROCK * 0.5)
#define BULLET_RECOIL_GHOUL_ROCK BULLET_RECOIL_SHOTGUN
#define BULLET_RECOIL_GHOUL_ROCK_HANDLOAD (BULLET_RECOIL_GHOUL_ROCK * BULLET_HANDLOAD_MULT_RECOIL)
#define BULLET_RECOIL_GHOUL_ROCK_MATCH (BULLET_RECOIL_GHOUL_ROCK * BULLET_MATCH_MULT_RECOIL)
#define BULLET_SPEED_GHOUL_ROCK (BULLET_SPEED_BASE * 0.25)
#define BULLET_SPEED_GHOUL_ROCK_HANDLOAD (BULLET_SPEED_GHOUL_ROCK * BULLET_HANDLOAD_MULT_SPEED)
#define BULLET_SPEED_GHOUL_ROCK_MATCH (BULLET_SPEED_GHOUL_ROCK * BULLET_MATCH_MULT_SPEED)
#define BULLET_WOUND_GHOUL_ROCK 2
#define BULLET_WOUND_GHOUL_ROCK_HANDLOAD (BULLET_WOUND_GHOUL_ROCK * BULLET_HANDLOAD_MULT_WOUND)
#define BULLET_WOUND_GHOUL_ROCK_MATCH (BULLET_WOUND_GHOUL_ROCK * BULLET_MATCH_MULT_WOUND)
#define BULLET_WOUND_GHOUL_ROCK_NAKED_MULT 2
#define RUBBERY_DAMAGE_GHOUL_ROCK (BULLET_DAMAGE_GHOUL_ROCK * RUBBERY_DAMAGE_MULT)
#define RUBBERY_STAMINA_GHOUL_ROCK (BULLET_DAMAGE_GHOUL_ROCK)
#define RUBBERY_RECOIL_GHOUL_ROCK (BULLET_RECOIL_GHOUL_ROCK * RUBBERY_RECOIL_MULT)
#define RUBBERY_WOUND_GHOUL_ROCK (BULLET_WOUND_GHOUL_ROCK * 4)

#define BULLET_DAMAGE_ARROW 40
#define BULLET_STAMINA_ARROW (BULLET_DAMAGE_ARROW * 0.5)
#define BULLET_RECOIL_ARROW 10
#define BULLET_SPEED_ARROW ARROW_SPEED_BASE
#define BULLET_WOUND_ARROW 5
#define BULLET_WOUND_ARROW_NAKED_MULT 10

#define BULLET_DAMAGE_ARROW_EXPLOSIVE 0
#define BULLET_STAMINA_ARROW_EXPLOSIVE 0
#define BULLET_RECOIL_ARROW_EXPLOSIVE 10
#define BULLET_SPEED_ARROW_EXPLOSIVE ARROW_SPEED_BASE
#define BULLET_WOUND_ARROW_EXPLOSIVE 0
#define BULLET_WOUND_ARROW_EXPLOSIVE_NAKED_MULT 0

/// Bullet damage falloff per tile defines
#define BULLET_FALLOFF "bullet falloff per tile"
#define BULLET_FALLOFF_PISTOL_LIGHT 3
#define BULLET_FALLOFF_PISTOL_MEDIUM 5
#define BULLET_FALLOFF_PISTOL_HEAVY 6
#define BULLET_FALLOFF_RIFLE_LIGHT 5
#define BULLET_FALLOFF_RIFLE_MEDIUM 10
#define BULLET_FALLOFF_RIFLE_HEAVY 10
#define BULLET_FALLOFF_SHOTGUN_PELLET 4
#define BULLET_FALLOFF_SHOTGUN_SLUG 2

/// Bullet damage falloff starting distance defines
#define BULLET_FALLOFF_START "bullet falloff start distance"
#define BULLET_FALLOFF_START_PISTOL_LIGHT 2
#define BULLET_FALLOFF_START_PISTOL_MEDIUM 4
#define BULLET_FALLOFF_START_PISTOL_HEAVY 5
#define BULLET_FALLOFF_START_RIFLE_LIGHT 3
#define BULLET_FALLOFF_START_RIFLE_MEDIUM 10
#define BULLET_FALLOFF_START_RIFLE_HEAVY 20
#define BULLET_FALLOFF_START_SHOTGUN_PELLET 0
#define BULLET_FALLOFF_START_SHOTGUN_SLUG 5

/// Bullet damage falloff default defines
#define BULLET_FALLOFF_DEFAULT_PISTOL_LIGHT list(BULLET_FALLOFF = BULLET_FALLOFF_PISTOL_LIGHT, BULLET_FALLOFF_START = BULLET_FALLOFF_START_PISTOL_LIGHT)
#define BULLET_FALLOFF_DEFAULT_PISTOL_MEDIUM list(BULLET_FALLOFF = BULLET_FALLOFF_PISTOL_MEDIUM, BULLET_FALLOFF_START = BULLET_FALLOFF_START_PISTOL_MEDIUM)
#define BULLET_FALLOFF_DEFAULT_PISTOL_HEAVY list(BULLET_FALLOFF = BULLET_FALLOFF_PISTOL_HEAVY, BULLET_FALLOFF_START = BULLET_FALLOFF_START_PISTOL_HEAVY)
#define BULLET_FALLOFF_DEFAULT_RIFLE_LIGHT list(BULLET_FALLOFF = BULLET_FALLOFF_RIFLE_LIGHT, BULLET_FALLOFF_START = BULLET_FALLOFF_START_RIFLE_LIGHT)
#define BULLET_FALLOFF_DEFAULT_RIFLE_MEDIUM list(BULLET_FALLOFF = BULLET_FALLOFF_RIFLE_MEDIUM, BULLET_FALLOFF_START = BULLET_FALLOFF_START_RIFLE_MEDIUM)
#define BULLET_FALLOFF_DEFAULT_RIFLE_HEAVY list(BULLET_FALLOFF = BULLET_FALLOFF_RIFLE_HEAVY, BULLET_FALLOFF_START = BULLET_FALLOFF_START_RIFLE_HEAVY)
#define BULLET_FALLOFF_DEFAULT_SHOTGUN_PELLET list(BULLET_FALLOFF = BULLET_FALLOFF_START_PISTOL_LIGHT, BULLET_FALLOFF_START = BULLET_FALLOFF_START_SHOTGUN_PELLET)
#define BULLET_FALLOFF_DEFAULT_SHOTGUN_SLUG list(BULLET_FALLOFF = BULLET_FALLOFF_SHOTGUN_PELLET, BULLET_FALLOFF_START = BULLET_FALLOFF_START_SHOTGUN_SLUG)

/// Minimum bullet damage that falloff can take it to
#define BULLET_FALLOFF_MIN_DAMAGE 3

/// Shotgun pellet count defines
#define SHOTGUN_PELLET_NEEDLER 5
#define SHOTGUN_PELLET_BASE 10
#define SHOTGUN_PELLET_IMPROVISED 8

/// Shotgun pellet spread defines
#define SHOTGUN_SPREAD_BASE 18
#define SHOTGUN_SPREAD_IMPROVISED 25

/// Bullet spread modifier defines
#define BULLET_SPREAD_BASE 2 // Base spread added from 'quality' ammo

/// Bullet spread modifier defines
#define BULLET_SPREAD_MATCH 0 // No extra spread~
#define BULLET_SPREAD_SURPLUS (BULLET_SPREAD_BASE) // Base spread
#define BULLET_SPREAD_HANDLOAD (BULLET_SPREAD_BASE * 2) // More spread!
#define BULLET_SPREAD_FLINTLOCK (BULLET_SPREAD_BASE * 4) // Morer spread!

/// Casing spread modifier defines
#define CASING_SPREAD_MATCH 0 // No extra spread~
#define CASING_SPREAD_SURPLUS (BULLET_SPREAD_BASE) // Base spread
#define CASING_SPREAD_HANDLOAD (BULLET_SPREAD_BASE * 2) // More spread!
#define CASING_SPREAD_FLINTLOCK (BULLET_SPREAD_BASE * 4) // Morer spread!

/// Bullet wound falloff defines
#define BULLET_WOUND_FALLOFF_PISTOL_LIGHT 0
#define BULLET_WOUND_FALLOFF_PISTOL_MEDIUM 2
#define BULLET_WOUND_FALLOFF_PISTOL_HEAVY 3
#define BULLET_WOUND_FALLOFF_RIFLE_LIGHT 0.5
#define BULLET_WOUND_FALLOFF_RIFLE_MEDIUM 0
#define BULLET_WOUND_FALLOFF_RIFLE_HEAVY 0
#define BULLET_WOUND_FALLOFF_SHOTGUN_PELLET 0
#define BULLET_WOUND_FALLOFF_SHOTGUN_SLUG 0

/// If you're naked, more wounds
#define BULLET_NAKED_RUBBERY_WOUND_MULT 0.5
#define BULLET_NAKED_WOUND_MULT 0.75

/// Bullet ammo type multiplier defines
/// Acid ammo
#define BULLET_DAMAGE_ACID 0.5
#define BULLET_STAMINA_ACID 0.5
#define BULLET_WOUND_ACID 2
#define BULLET_NAKED_WOUND_ACID 2

/// Fire ammo
#define BULLET_DAMAGE_FIRE 0.5
#define BULLET_STAMINA_FIRE 0.5
#define BULLET_WOUND_FIRE 1
#define BULLET_NAKED_WOUND_FIRE 0

/// Shock ammo
#define BULLET_DAMAGE_SHOCK 0.5
#define BULLET_STAMINA_SHOCK 0.5
#define BULLET_WOUND_SHOCK 0
#define BULLET_NAKED_WOUND_SHOCK 0

/// Microshapnel ammo
#define BULLET_DAMAGE_MICROSHRAPNEL 0.5
#define BULLET_STAMINA_MICROSHRAPNEL 0.5
#define BULLET_WOUND_MICROSHRAPNEL 2.5
#define BULLET_NAKED_WOUND_MICROSHRAPNEL 2.5

/// Explosive ammo
#define BULLET_DAMAGE_EXPLOSIVE 0.5
#define BULLET_STAMINA_EXPLOSIVE 0.5
#define BULLET_WOUND_EXPLOSIVE 2 // I mean it explodes in you
#define BULLET_NAKED_WOUND_EXPLOSIVE 2

/// Poison ammo
#define BULLET_DAMAGE_POISON 0.5
#define BULLET_STAMINA_POISON 0.5
#define BULLET_WOUND_POISON 0
#define BULLET_NAKED_WOUND_POISON 0

/* * * * * * * * *
 * Gun  defines! *
 * * * * * * * * */

/// Gun Firemodes
#define GUN_FIREMODE_SEMIAUTO 1
#define GUN_FIREMODE_BURST 2
#define GUN_FIREMODE_AUTO 3

//#define RECOIL_SPREAD_CALC(x)  (0.0075 * (x ** 4)) // Funky way of exponentiating bullet spread from recoil // funky recoil kidna turbofucks things in wierd says, maybe
#define RECOIL_SPREAD_CALC(x) (x)
#define MAX_ACCURACY_OFFSET 45 //It's both how big gun recoil can build up, and how hard you can miss. Is a plus-or-minus
#define MAX_RETICLE_SIZE 32 // it can go offscreen, which is less than ideal

/// Max spread recoil can add
#define GUN_RECOIL_MAX_SPREAD MAX_ACCURACY_OFFSET

/// Sawed-off recoil modifier
#define SAWEDOFF_RECOIL_MULT 2

/// Hobogun recoil modifier
#define HOBO_RECOIL_MULT 2

// Gun Akimbo Spread modifier
#define GUN_AKIMBO_RECOIL_MOD 2

// If their other hand is full, multiply recoil by this much
#define GUN_FULL_OTHER_HAND_RECOIL_MOD 2

/// Gun recoil timeout Base
#define GUN_RECOIL_TIMEOUT_BASE (2 SECONDS)

/// Gun recoil timeout modifiers
#define GUN_RECOIL_TIMEOUT_INSTANT (GUN_RECOIL_TIMEOUT_BASE * 0.1)
#define GUN_RECOIL_TIMEOUT_QUICK (GUN_RECOIL_TIMEOUT_BASE * 0.75)
#define GUN_RECOIL_TIMEOUT_NORMAL (GUN_RECOIL_TIMEOUT_BASE * 1)
#define GUN_RECOIL_TIMEOUT_LONG (GUN_RECOIL_TIMEOUT_BASE * 1.5)
#define GUN_RECOIL_TIMEOUT_LONGER (GUN_RECOIL_TIMEOUT_BASE * 2)

/// Gun spread modifiers
#define GUN_SPREAD_NONE 0
#define GUN_SPREAD_NORMAL 1
#define GUN_SPREAD_POOR (GUN_SPREAD_NORMAL * 2)
#define GUN_SPREAD_AWFUL (GUN_SPREAD_NORMAL * 3)
#define GUN_SPREAD_SUPERAWFUL (GUN_SPREAD_NORMAL * 4)

/// Time after you draw a gun that you're able to shoot it
#define GUN_AIMING_TIME (1.5 SECONDS)

/// Gun draw time modifiers
#define GUN_DRAW_QUICK (GUN_AIMING_TIME * 0.1) // Draw, pardner
#define GUN_DRAW_NORMAL (GUN_AIMING_TIME * 1)
#define GUN_DRAW_LONG (GUN_AIMING_TIME * 1.5)

/// Gun weapon weight
#define GUN_ONE_HAND_AKIMBO 1
#define GUN_ONE_HAND_ONLY 2
#define GUN_TWO_HAND_ONLY 3

/// Gun bullet damage base
/// Multiplies the gun's projectile damage
#define GUN_EXTRA_DAMAGE_0 1
#define GUN_EXTRA_DAMAGE_T1 1.10
#define GUN_EXTRA_DAMAGE_T2 1.15
#define GUN_EXTRA_DAMAGE_T3 1.25
#define GUN_EXTRA_DAMAGE_T4 1.35
#define GUN_EXTRA_DAMAGE_T5 1.50
#define GUN_EXTRA_DAMAGE_T6 1.75 // :^) ~Fenny

/// Also multiplies the gun's projectile damage, but so it does less damage
#define GUN_LESS_DAMAGE_T1 0.90
#define GUN_LESS_DAMAGE_T2 0.85
#define GUN_LESS_DAMAGE_T3 0.75
#define GUN_LESS_DAMAGE_T4 0.65
#define GUN_LESS_DAMAGE_T5 0.50
#define GUN_LESS_DAMAGE_T6 0.35
#define GUN_LESS_DAMAGE_T7 0.25

//custom gun damage debuffs for later usage if gun needs a fine tuning.
#define GUN_LESS_DAMAGE_C1 0.55
#define GUN_LESS_DAMAGE_C2 0.45
#define GUN_LESS_DAMAGE_C3 0.40
#define GUN_LESS_DAMAGE_C4 0.30

/// Gun melee force base
#define GUN_MELEE_FORCE_BASE 12

/// Gun weapon weight
#define GUN_MELEE_FORCE_PISTOL_LIGHT (GUN_MELEE_FORCE_BASE * 1) // 12
#define GUN_MELEE_FORCE_PISTOL_HEAVY (GUN_MELEE_FORCE_BASE * 1.25) //15
#define GUN_MELEE_FORCE_RIFLE_LIGHT (GUN_MELEE_FORCE_BASE * 1.5) //18
#define GUN_MELEE_FORCE_RIFLE_HEAVY (GUN_MELEE_FORCE_BASE * 2) // 24
#define GUN_MELEE_FORCE_RIFLE_GUNBLADE (GUN_MELEE_FORCE_BASE * 2.5) //30
#define GUN_MELEE_FORCE_RIFLE_HEAVIER (GUN_MELEE_FORCE_BASE * 3) //36

/// Gun slowdown
#define GUN_SLOWDOWN_NONE 0.1
#define GUN_SLOWDOWN_PISTOL_LIGHT 0.05
#define GUN_SLOWDOWN_PISTOL_MEDIUM 0.10
#define GUN_SLOWDOWN_PISTOL_HEAVY 0.15
#define GUN_SLOWDOWN_REVOLVER_LIGHT 0.10
#define GUN_SLOWDOWN_REVOLVER_HEAVY 0.15
#define GUN_SLOWDOWN_REPEATER 0.20
#define GUN_SLOWDOWN_CARBINE 0.20
#define GUN_SLOWDOWN_SMG_LIGHT 0.10
#define GUN_SLOWDOWN_SMG_HEAVY 0.25
#define GUN_SLOWDOWN_RIFLE_BOLT 0.30
#define GUN_SLOWDOWN_RIFLE_LIGHT_SEMI 0.25
#define GUN_SLOWDOWN_RIFLE_LIGHT_AUTO 0.35
#define GUN_SLOWDOWN_RIFLE_MEDIUM_SEMI 0.30
#define GUN_SLOWDOWN_RIFLE_MEDIUM_AUTO 0.40
#define GUN_SLOWDOWN_RIFLE_LMG 0.60
#define GUN_SLOWDOWN_RIFLE_GAUSS 1
#define GUN_SLOWDOWN_SHOTGUN_FIXED 0.05
#define GUN_SLOWDOWN_SHOTGUN_PUMP 0.10
#define GUN_SLOWDOWN_SHOTGUN_AUTO 0.40

/// Cock length
/// Delay between cocking your gun
#define GUN_COCK_BASE (1 SECONDS)

#define GUN_COCK_INSTANT 0.1
#define GUN_COCK_SHOTGUN_BASE (GUN_COCK_BASE)
#define GUN_COCK_SHOTGUN_FAST (GUN_COCK_BASE * 0.4)
#define GUN_COCK_SHOTGUN_LIGHTNING (GUN_COCK_BASE * 0.1)
#define GUN_COCK_RIFLE_BASE (GUN_COCK_BASE)
#define GUN_COCK_RIFLE_FAST (GUN_COCK_BASE * 0.75)
#define GUN_COCK_RIFLE_LIGHTNING (GUN_COCK_BASE * 0.5)

/// Refire speed multiplier for manual action guns, cus we no longer care about your cock length
#define GUN_RIFLEMAN_REFIRE_DELAY_MULT 0.8

/// Refire speed multiplier for manual action guns if you're not a pr0 and click-to-cycle it
#define GUN_AUTOPUMP_REFIRE_DELAY_MULT 1.8

/// Projectiles define the recoil amount, guns modify the recoil based on wieldedness

#define BASE_MOVEMENT_RECOIL_MULT 1
#define SCOOT_FACTOR(x) (x * BASE_MOVEMENT_RECOIL_MULT)
/// Negative scoot factor (better spread while moving) can only reduce shoot recoil by this percent of the shoot recoil
#define SCOOT_MAX_REDUCTION 0.75

/// TODO: make these actually work
#define BASE_SPRAY_RECOIL_MULT 1
#define SPRAY_FACTOR(x) (x * BASE_SPRAY_RECOIL_MULT)
/// Negative spray factor (better spread while moving) can only reduce shoot recoil by this percent of the shoot recoil
#define SPRAY_MAX_REDUCTION 0.25
#define SPRAY_SHOTS_PER_SECOND_THRESHOLD 3

#define RECOIL_SOFTCAP (MAX_ACCURACY_OFFSET * 1.5) // shrug

/////////////////////////////////// 1HANDED , 2HANDED, MOVE RECOIL MULT
#define HANDGUN_RECOIL(x,y)     list(1   * x, 0.9 * y, SCOOT_FACTOR(0)   , SPRAY_FACTOR(1.2) ) // Mobile, but not spammable
#define AUTOPISTOL_RECOIL(x,y)  list(1.3 * x, 1   * y, SCOOT_FACTOR(0.5) , SPRAY_FACTOR(1)   ) // negative numbers actually decrease your output spread while moving!
#define SMG_RECOIL(x,y)         list(1   * x, 1   * y, SCOOT_FACTOR(-1)  , SPRAY_FACTOR(0.75)) // made for spraying
#define CARBINE_RECOIL(x,y)     list(2   * x, 0.8 * y, SCOOT_FACTOR(0.3) , SPRAY_FACTOR(1)   )
#define AUTOCARBINE_RECOIL(x,y) list(3   * x, 0.9 * y, SCOOT_FACTOR(0.5) , SPRAY_FACTOR(1)   )
#define SHOTGUN_RECOIL(x,y)     list(2   * x, 0.5 * y, SCOOT_FACTOR(0)   , SPRAY_FACTOR(2)   )
#define RIFLE_RECOIL(x,y)       list(5   * x, 0.5 * y, SCOOT_FACTOR(2)   , SPRAY_FACTOR(2)   )
#define AUTORIFLE_RECOIL(x,y)   list(5   * x, 0.7 * y, SCOOT_FACTOR(0.5) , SPRAY_FACTOR(1)   )
#define AUTOSHOTGUN_RECOIL(x,y) list(10  * x, 1   * y, SCOOT_FACTOR(-2)  , SPRAY_FACTOR(1)   )
#define LMG_RECOIL(x,y)         list(5   * x, 0.5 * y, SCOOT_FACTOR(10)  , SPRAY_FACTOR(-0.3)) // Everyone grab a negev, we rushin B
#define HMG_RECOIL(x,y)         list(10  * x, 0.3 * y, SCOOT_FACTOR(20)  , SPRAY_FACTOR(-0.5))

#define LASER_HANDGUN_RECOIL_RARE(x,y) list(0.2 * x, 0.1 * y, SCOOT_FACTOR(0)   , SPRAY_FACTOR(1.2) ) // Mobile, but not spammable
#define LASER_HANDGUN_RECOIL(x,y)      list(1   * x, 1   * y, SCOOT_FACTOR(0)   , SPRAY_FACTOR(1.2) ) // Mobile, but not spammable
#define LASER_SMG_RECOIL(x,y)          list(1.5 * x, 1   * y, SCOOT_FACTOR(-1)  , SPRAY_FACTOR(0.75)) // made for spraying
#define LASER_CARBINE_RECOIL(x,y)      list(2   * x, 0.8 * y, SCOOT_FACTOR(0.5) , SPRAY_FACTOR(1)   )
#define LASER_RIFLE_RECOIL(x,y)        list(2   * x, 0.2 * y, SCOOT_FACTOR(0.5) , SPRAY_FACTOR(1)   )
#define LASER_AUTORIFLE_RECOIL(x,y)    list(4   * x, 0.5 * y, SCOOT_FACTOR(0.5) , SPRAY_FACTOR(1)   )

/// If you dont shoot for this long, your recoil is decreased by an exponential rate
#define RECOIL_SHOOT_TIME 0.8 SECONDS
/// If you dont move for this long, your next step won't increase recoil (and your recoil will decrease by an exponential rate)
#define RECOIL_SCOOCH_TIME 0.8 SECONDS
// The number of free tiles you can move in Scoochmode
#define RECOIL_SCOOCH_TILES 2

#define RECOIL_INDEX_UNWIELDED 1
#define RECOIL_INDEX_WIELDED 2
#define RECOIL_INDEX_SCOOT 3
#define RECOIL_INDEX_SPRAY 4
#define IS_RECOIL_TAG(tag) (istext(tag) && findtext(tag, RECOIL_TAG_DIVIDER))
#define IS_RECOIL_LIST(list) (islist(list) && length(list) == 4)

#define RECOIL_TAG_DIVIDER "%"
#define RECOIL_ARGS2TAG(unwielded, wielded, scoot, spray) jointext(list(unwielded, wielded, scoot, spray), RECOIL_TAG_DIVIDER)
#define RECOIL_LIST2TAG(list) jointext(list, RECOIL_TAG_DIVIDER)
#define RECOIL_TAG2LIST(tag) splittext(tag, RECOIL_TAG_DIVIDER)

#define RECOIL_TAG_DEFAULT "1[RECOIL_TAG_DIVIDER]1[RECOIL_TAG_DIVIDER]1[RECOIL_TAG_DIVIDER]1"
#define RECOIL_LIST_DEFAULT list(1, 1, 1, 1)

#define RECOIL_REDUCTION_BASE_PER_SECOND 1
#define RECOIL_REDUCTION_MULT 1
#define RECOIL_REDUCTION_TICK2SECOND(base, tick, mult) (round((base * (0.1 * tick) * mult), 0.005))

/// Converts rounds per minute to deciseconds per shot
#define RPM_TO_FIRE_DELAY(rpm) ((60 / rpm) * 10)

#define GUN_FIRE_RATE_40 RPM_TO_FIRE_DELAY(80) // 80 RPM = 7.5 deciseconds per shot | Fenny said to double them all! - Jaeger
#define GUN_FIRE_RATE_75 RPM_TO_FIRE_DELAY(150) // 150 RPM = 4 deciseconds per shot
#define GUN_FIRE_RATE_100 RPM_TO_FIRE_DELAY(200) // 200 RPM = 3 deciseconds per shot
#define GUN_FIRE_RATE_150 RPM_TO_FIRE_DELAY(300) // 300 RPM = 2 deciseconds per shot
#define GUN_FIRE_RATE_250 RPM_TO_FIRE_DELAY(350) // 350 RPM = 2,5 deciseconds probably ---> Tox RPM, adjust if needed.
#define GUN_FIRE_RATE_200 RPM_TO_FIRE_DELAY(400) // 400 RPM = 1.5 deciseconds per shot
#define GUN_FIRE_RATE_300 RPM_TO_FIRE_DELAY(600) // 600 RPM = 1 deciseconds per shot
#define GUN_FIRE_RATE_400 RPM_TO_FIRE_DELAY(800) // 800 RPM = 0.75 deciseconds per shot
#define GUN_FIRE_RATE_600 RPM_TO_FIRE_DELAY(1200) // 1200 RPM = 0.5 decisecond per shot
#define GUN_FIRE_RATE_800 RPM_TO_FIRE_DELAY(1600) // 1600 RPM = 0.375 deciseconds per shot
#define GUN_FIRE_RATE_1000 RPM_TO_FIRE_DELAY(2000) // 2000 RPM = 0.3 deciseconds per shot
#define GUN_FIRE_RATE_1200 RPM_TO_FIRE_DELAY(2400) // 2400 RPM = 0.25 deciseconds per shot

/// Gun fire delay Base
#define GUN_FIRE_DELAY_BASE (1 SECONDS)

/// Gun fire delay modifiers
#define GUN_FIRE_DELAY_FASTEST GUN_FIRE_RATE_600
#define GUN_FIRE_DELAY_FASTER GUN_FIRE_RATE_300
#define GUN_FIRE_DELAY_FAST GUN_FIRE_RATE_150
#define GUN_FIRE_DELAY_NORMAL GUN_FIRE_RATE_100
#define GUN_FIRE_DELAY_SLOW GUN_FIRE_RATE_75
#define GUN_FIRE_DELAY_SLOWER GUN_FIRE_RATE_40

/// Gun autofire delay Base
#define GUN_AUTOFIRE_DELAY_BASE 1

/// Gun fire delay modifiers
#define GUN_AUTOFIRE_DELAY_FASTEST GUN_FIRE_RATE_800
#define GUN_AUTOFIRE_DELAY_FASTER GUN_FIRE_RATE_600
#define GUN_AUTOFIRE_DELAY_FAST GUN_FIRE_RATE_400
#define GUN_AUTOFIRE_DELAY_NORMAL GUN_FIRE_RATE_300
#define GUN_AUTOFIRE_DELAY_SLOW GUN_FIRE_RATE_200
#define GUN_AUTOFIRE_DELAY_SLOWish GUN_FIRE_RATE_250
#define GUN_AUTOFIRE_DELAY_SLOWER GUN_FIRE_RATE_150

/// Gun burstfire delay Base
#define GUN_BURSTFIRE_DELAY_BASE 1

/// Gun fire delay modifiers
#define GUN_BURSTFIRE_DELAY_FASTEST GUN_FIRE_RATE_1200
#define GUN_BURSTFIRE_DELAY_FASTER GUN_FIRE_RATE_1000
#define GUN_BURSTFIRE_DELAY_FAST GUN_FIRE_RATE_800
#define GUN_BURSTFIRE_DELAY_NORMAL GUN_FIRE_RATE_600
#define GUN_BURSTFIRE_DELAY_SLOW GUN_FIRE_RATE_400
#define GUN_BURSTFIRE_DELAY_SLOWER GUN_FIRE_RATE_300

/// Bullet zone favoring defines
/// High accuracy, generally goes where you mean to put it, for precision rifles and such
#define ZONE_WEIGHT_PRECISION "precision_aim"
/// Typical accuracy, based a bit on range
#define ZONE_WEIGHT_SEMI_AUTO "semiauto_aim"
/// Heavily weights limbs after its effective distance
#define ZONE_WEIGHT_AUTOMATIC "automatic_aim"
/// Always weights limbs heavily
#define ZONE_WEIGHT_SHOTGUN "shotgun_aim"
/// Always defers to the gun's setting, defaults to semi-auto if not defined
#define ZONE_WEIGHT_GUNS_CHOICE "gun's_choice"

/// Typical accuracy falloff
#define ZONE_WEIGHT_FALLOFF_SEMI_AUTO 7
/// Zone accuracy falls off quickly
#define ZONE_WEIGHT_FALLOFF_AUTOMATIC 20
/// You're hitting limbs most of the time
#define ZONE_WEIGHT_FALLOFF_SHOTGUN 100

/// Default zone weight list
#define ZONE_WEIGHT_LIST_DEFAULT list(\
	BODY_ZONE_HEAD = 6,\
	BODY_ZONE_CHEST = 6,\
	BODY_ZONE_L_ARM = 22,\
	BODY_ZONE_R_ARM = 22,\
	BODY_ZONE_L_LEG = 22,\
	BODY_ZONE_R_LEG = 22)
/// Precision zone weight list
#define ZONE_WEIGHT_LIST_PRECISION list(\
	BODY_ZONE_HEAD = 20,\
	BODY_ZONE_CHEST = 40,\
	BODY_ZONE_L_ARM = 5,\
	BODY_ZONE_R_ARM = 5,\
	BODY_ZONE_L_LEG = 5,\
	BODY_ZONE_R_LEG = 5)
/// Autofire zone weight list
#define ZONE_WEIGHT_LIST_AUTOMATIC list(\
	BODY_ZONE_HEAD = 1,\
	BODY_ZONE_CHEST = 3,\
	BODY_ZONE_L_ARM = 22,\
	BODY_ZONE_R_ARM = 22,\
	BODY_ZONE_L_LEG = 22,\
	BODY_ZONE_R_LEG = 22)
/// Pellet zone weight list
#define ZONE_WEIGHT_LIST_SHOTGUN list(\
	BODY_ZONE_HEAD = 1,\
	BODY_ZONE_CHEST = 1,\
	BODY_ZONE_L_ARM = 22,\
	BODY_ZONE_R_ARM = 22,\
	BODY_ZONE_L_LEG = 22,\
	BODY_ZONE_R_LEG = 22)

/// Gun skill flags
/// Gun is affected by rifleman skill
#define AFFECTED_BY_FAST_PUMP (1<<0)
/// If you autopump this gun, it'll have a debuff to its refire rate till you fire again
#define AFFECTED_BY_AUTO_PUMP (1<<1)

/// Gun cooldown mod flags
/// Gun is slower to refire if you autopump it (without fast pump)
#define GUN_AUTO_PUMPED (1<<0)

/// Gun handedness defines -- for picking which direction to toss casings
#define GUN_EJECTOR_RIGHT 1
#define GUN_EJECTOR_LEFT 2
#define GUN_EJECTOR_ANY 3

/// Gun misfire actions
#define GUN_MF_CHANCE "misfire_chance"

/// Gun does damage when it misfires
/// Gun hurts you define
#define GUN_MF_HURTS_YOU "pow_ow"
/// Gun hurts you low damage define
#define GUN_MF_HURTS_YOU_DAMAGE_LOW "low_end_damage_it_hurts_you_you_when_it_pows"
/// Gun hurts you high damage define
#define GUN_MF_HURTS_YOU_DAMAGE_HIGH "high_end_damage_it_hurts_you_you_when_it_pows"
/// Gun hurts you with this type of damage define
#define GUN_MF_HURTS_YOU_DAMAGE_TYPE "damage_type_it_hurts_you_you_when_it_pows"
/// Varied minimum list
#define GUN_MISFIRE_HURTS_USER(chance, dmg_low, dmg_high, dmg_type) GUN_MF_HURTS_YOU = list(\
	GUN_MF_CHANCE = chance,\
	GUN_MF_HURTS_YOU_DAMAGE_LOW = dmg_low,\
	GUN_MF_HURTS_YOU_DAMAGE_HIGH = dmg_high,\
	GUN_MF_HURTS_YOU_DAMAGE_TYPE = dmg_type)

/// Gun yeets itself out of your hand when it misfires
/// Gun yeets define
#define GUN_MF_YEET "pow_yeet"
/// Gun yeets the gun entry
#define GUN_MISFIRE_THROWS_GUN(chance) GUN_MF_YEET = list(\
	GUN_MF_CHANCE = chance)

/// Gun dumps out its ammo
/// Gun dump define
#define GUN_MF_DUMP "pow_dump"
/// Gun dump throw it define
#define GUN_MF_DUMP_THROW "dump_yeet_chance"
/// Gun dump the gun entry
#define GUN_MISFIRE_UNLOADS_GUN(chance, throw_chance) GUN_MF_DUMP = list(\
	GUN_MF_CHANCE = chance,\
	GUN_MF_DUMP_THROW = throw_chance)

/// cooldown for being spammed with messages you're holding the stupid gun wrong
#define GUN_HOLD_IT_RIGHT_MESSAGE_ANTISPAM_TIME 10 SECONDS

/// cooldown for being spammed with messages that you shot the gun
#define GUN_SHOOT_MESSAGE_ANTISPAM_TIME 0.5 SECONDS

/// Unarmed Damage Defines
#define PUNCH_DAMAGE_LOW 1
#define PUNCH_DAMAGE_MAX 10
#define PUNCH_DAMAGE_AVERAGE FLOOR((PUNCH_DAMAGE_LOW + PUNCH_DAMAGE_MAX) * 0.5, 1)
#define IRON_FIST_PUNCH_DAMAGE_LOW 6
#define IRON_FIST_PUNCH_DAMAGE_MAX 12
#define IRON_FIST_PUNCH_DAMAGE_AVERAGE FLOOR((IRON_FIST_PUNCH_DAMAGE_LOW + IRON_FIST_PUNCH_DAMAGE_MAX) * 0.5, 1)
#define STEEL_FIST_PUNCH_DAMAGE_LOW 10
#define STEEL_FIST_PUNCH_DAMAGE_MAX 16
#define STEEL_FIST_PUNCH_DAMAGE_AVERAGE FLOOR((STEEL_FIST_PUNCH_DAMAGE_LOW + STEEL_FIST_PUNCH_DAMAGE_MAX) * 0.5, 1)

//weapon class defines for standardized stats
#define WEAPON_CLASS_TINY list(\
"w_class" = WEIGHT_CLASS_TINY,\
"slot_flags" = INV_SLOTBIT_BELT,\
"slowdown" = GUN_SLOWDOWN_PISTOL_LIGHT,\
"force" = GUN_MELEE_FORCE_PISTOL_LIGHT,\
"draw_time" = GUN_DRAW_QUICK,\
)
#define WEAPON_CLASS_SMALL list(\
"w_class" = WEIGHT_CLASS_SMALL,\
"slot_flags" = INV_SLOTBIT_BELT,\
"slowdown" = GUN_SLOWDOWN_PISTOL_MEDIUM,\
"force" = GUN_MELEE_FORCE_PISTOL_LIGHT,\
"draw_time" = GUN_DRAW_NORMAL,\
)
#define WEAPON_CLASS_NORMAL list(\
"w_class" = WEIGHT_CLASS_NORMAL,\
"slot_flags" = INV_SLOTBIT_BELT,\
"slowdown" = GUN_SLOWDOWN_PISTOL_HEAVY,\
"force" = GUN_MELEE_FORCE_PISTOL_HEAVY,\
"draw_time" = GUN_DRAW_NORMAL,\
)
#define WEAPON_CLASS_CARBINE list(\
"w_class" = WEIGHT_CLASS_BULKY,\
"slot_flags" = INV_SLOTBIT_BELT | INV_SLOTBIT_BACK,\
"slowdown" = GUN_SLOWDOWN_CARBINE,\
"force" = GUN_MELEE_FORCE_RIFLE_LIGHT,\
"draw_time" = GUN_DRAW_LONG,\
)
#define WEAPON_CLASS_RIFLE list(\
"w_class" = WEIGHT_CLASS_BULKY,\
"slot_flags" = INV_SLOTBIT_BACK,\
"slowdown" = GUN_SLOWDOWN_RIFLE_BOLT,\
"force" = GUN_MELEE_FORCE_RIFLE_HEAVY,\
"draw_time" = GUN_DRAW_LONG,\
)

/// Musket defines
#define FLINTLOCK_PISTOL_RELOAD_TIME 0.1 SECONDS
#define FLINTLOCK_MINIMUSKET_RELOAD_TIME 0.2 SECONDS
#define FLINTLOCK_MUSKET_RELOAD_TIME 1 SECONDS

#define FLINTLOCK_PISTOL_PREFIRE_TIME 0.1 SECONDS
#define FLINTLOCK_MINIMUSKET_PREFIRE_TIME 0.2 SECONDS
#define FLINTLOCK_MUSKET_PREFIRE_TIME 0.2 SECONDS

/// Multipliers, if flintlock has a prefire time of 0.5 seconds, and the multiplier is 2, then the prefire time standard deviation is 1 second
#define FLINTLOCK_PISTOL_PREFIRE_STD 0.1 SECONDS
#define FLINTLOCK_MINIMUSKET_PREFIRE_STD 0.2 SECONDS
#define FLINTLOCK_MUSKET_PREFIRE_STD 0.2 SECONDS

/// Matchlock defines
#define MATCHLOCK_PISTOL_RELOAD_TIME 0.5 SECONDS
#define MATCHLOCK_MINIMUSKET_RELOAD_TIME 2 SECONDS
#define MATCHLOCK_MUSKET_RELOAD_TIME 2 SECONDS
#define MATCHLOCK_BOMBARD_RELOAD_TIME 3 SECONDS

#define MATCHLOCK_PISTOL_PREFIRE_TIME 0.5 SECONDS
#define MATCHLOCK_MINIMUSKET_PREFIRE_TIME 0.7 SECONDS
#define MATCHLOCK_MUSKET_PREFIRE_TIME 1 SECONDS
#define MATCHLOCK_BOMBARD_PREFIRE_TIME 2 SECONDS

/// Multipliers, if matchlock has a prefire time of 0.5 seconds, and the multiplier is 2, then the prefire time standard deviation is 1 second
#define MATCHLOCK_PISTOL_PREFIRE_STD 0.3 SECONDS
#define MATCHLOCK_MINIMUSKET_PREFIRE_STD 0.4 SECONDS
#define MATCHLOCK_MUSKET_PREFIRE_STD 0.5 SECONDS
#define MATCHLOCK_BOMBARD_PREFIRE_STD 0.8 SECONDS
