
#define ENGSEC			(1<<0)

#define CAPTAIN			(1<<0)
#define HOS				(1<<1)
#define WARDEN			(1<<2)
#define DETECTIVE		(1<<3)
#define OFFICER			(1<<4)
#define CHIEF			(1<<5)
#define ENGINEER		(1<<6)
#define ATMOSTECH		(1<<7)
#define ROBOTICIST		(1<<8)
#define AI_JF			(1<<9)
#define CYBORG			(1<<10)


#define MEDSCI			(1<<1)

#define RD_JF			(1<<0)
#define SCIENTIST		(1<<1)
#define CHEMIST			(1<<2)
#define CMO_JF			(1<<3)
#define DOCTOR			(1<<4)
#define GENETICIST		(1<<5)
#define VIROLOGIST		(1<<6)
#define PARAMEDIC		(1<<7)


#define CIVILIAN		(1<<2)

#define HOP				(1<<0)
#define BARTENDER		(1<<1)
#define BOTANIST		(1<<2)
#define COOK			(1<<3)
#define JANITOR			(1<<4)
#define CURATOR			(1<<5)
#define QUARTERMASTER	(1<<6)
#define CARGOTECH		(1<<7)
#define MINER			(1<<8)
#define LAWYER			(1<<9)
#define CHAPLAIN		(1<<10)
#define CLOWN			(1<<11)
#define MIME			(1<<12)
#define ASSISTANT		(1<<13)

//F13

#define NCR				(1<<3)

#define F13COLONEL		 (1<<0)
#define F13CAPTAIN		 (1<<1)
#define F13LIEUTENANT    (1<<2)
#define	F13FIRSTSERGEANT (1<<3)
#define F13SERGEANT		 (1<<4)
#define F13CORPORAL		 (1<<5)
#define F13SPECIALIST	 (1<<6)
#define F13TROOPER		 (1<<7)
#define F13REARECHELON	 (1<<8)
#define F13NCROFFDUTY    (1<<9)
#define F13VETRANGER	 (1<<10)
#define F13RANGER	 	 (1<<11)

#define LEGION			(1<<4)

#define F13LEGATE		(1<<0)
#define F13CENTURION	(1<<1)
#define F13ORATOR		(1<<2)
#define F13PRIESTESS 	(1<<3)
#define F13DECANREC		(1<<4)
#define F13DECAN		(1<<5)
#define F13DECANVET		(1<<6)
#define F13VEXILLARIUS	(1<<7)
#define F13EXPLORER		(1<<8)
#define F13VENATOR		(1<<9)
#define F13VETLEGIONARY	(1<<10)
#define F13LEGIONARY	(1<<11)
#define F13RECRUITLEG	(1<<12)
#define F13AUXILIA		(1<<13)
#define F13LEGIONSLAVE	(1<<14)
#define F13SLAVEMASTER	(1<<15)

#define BOS				(1<<5)

#define F13ELDER		(1<<0)
#define F13SENTINEL		(1<<1)
#define F13SENIORPALADIN	(1<<2)
#define F13PALADIN		(1<<3)
#define F13KNIGHTCAPTAIN	(1<<4)
#define F13SENIORKNIGHT	(1<<5)
#define F13KNIGHT		(1<<6)
#define F13HEADSCRIBE	(1<<7)
#define F13SENIORSCRIBE (1<<8)
#define F13SCRIBE		(1<<9)
#define F13INITIATE		(1<<10)
#define F13OFFDUTYBOS	(1<<11)

#define DEN				(1<<6)

#define F13SHERIFF		(1<<0)
#define F13DENDOC       (1<<1)
#define F13SETTLER		(1<<2)
#define F13FARMER		(1<<3)
#define F13PROSPECTOR	(1<<4)
#define F13DEPUTY		(1<<5)
#define F13MAYOR		(1<<6)
#define F13PREACHER		(1<<7)
#define F13SHOPKEEPER	(1<<8)
#define F13FAITHFUL		(1<<9) // WHAT IS BITFLAG. WHAT DOES IT DO. WHERE IS THIS INFO USED.
#define F13BANKER		(1<<10)	// IDK MAN BUT IT SEEMS IMPORTANT
#define F13BARKEEP		(1<<11)

#define VAULT			(1<<7)

#define F13OVERSEER		(1<<0)
#define F13HOS			(1<<1)
#define F13DOCTOR		(1<<2)
#define F13VAULTSCIENTIST	(1<<3)
#define F13OFFICER		(1<<4)
#define F13VAULTENGINEER	(1<<5)
#define F13DWELLER		(1<<6)
#define F13AI			(1<<7)
#define F13CYBORG		(1<<8)

#define WASTELAND		(1<<8)

#define F13CULTLEADER	(1<<0)
#define F13WASTELANDER	(1<<1)
#define F13RAIDER		(1<<2)
#define F13PUSHER		(1<<3)
#define F13PUNRAIDER	(1<<4)
#define F13DETECTIVE	(1<<5)
#define EVENTCOVEN		(1<<6)

#define ENCLAVE			(1<<9)

#define F13USCOMMANDER	(1<<0)
#define F13USMEDIC		(1<<1)
#define F13USPRIVATE	(1<<2)
#define F13USSCIENTIST	(1<<3)
#define F13USENGINEER	(1<<4)
#define F13USCOLONIST	(1<<5)

#define TRIBAL			(1<<10)

#define F13CHIEF		(1<<0)
#define F13SHAMAN		(1<<1)
#define F13HHUNTER		(1<<2)
#define F13VILLAGER		(1<<3)
#define F13HUNTER		(1<<4)

#define FOLLOWERS		(1<<11)

#define	F13LEADPRACTITIONER	(1<<0)
#define	F13PRACTITIONER	(1<<1)
#define F13FOLLOWERGUARD	(1<<2)
#define F13FOLLOWERVOLUNTEER	(1<<3)
#define F13PROFESSOR	(1<<4)


#define JOB_AVAILABLE 0
#define JOB_UNAVAILABLE_GENERIC 1
#define JOB_UNAVAILABLE_BANNED 2
#define JOB_UNAVAILABLE_PLAYTIME 3
#define JOB_UNAVAILABLE_ACCOUNTAGE 4
#define JOB_UNAVAILABLE_SLOTFULL 5
#define JOB_UNAVAILABLE_SPECIESLOCK 6

#define DEFAULT_RELIGION "Christianity"
#define DEFAULT_DEITY "Space Jesus"

#define JOB_DISPLAY_ORDER_DEFAULT 0

#define JOB_DISPLAY_ORDER_ASSISTANT 1
#define JOB_DISPLAY_ORDER_CAPTAIN 2
#define JOB_DISPLAY_ORDER_HEAD_OF_PERSONNEL 3
#define JOB_DISPLAY_ORDER_QUARTERMASTER 4
#define JOB_DISPLAY_ORDER_CARGO_TECHNICIAN 5
#define JOB_DISPLAY_ORDER_SHAFT_MINER 6
#define JOB_DISPLAY_ORDER_BARTENDER 7
#define JOB_DISPLAY_ORDER_COOK 8
#define JOB_DISPLAY_ORDER_BOTANIST 9
#define JOB_DISPLAY_ORDER_JANITOR 10
#define JOB_DISPLAY_ORDER_CLOWN 11
#define JOB_DISPLAY_ORDER_MIME 12
#define JOB_DISPLAY_ORDER_CURATOR 13
#define JOB_DISPLAY_ORDER_LAWYER 14
#define JOB_DISPLAY_ORDER_CHAPLAIN 15
//#define JOB_DISPLAY_ORDER_AI 16
//#define JOB_DISPLAY_ORDER_CYBORG 17
#define JOB_DISPLAY_ORDER_CHIEF_ENGINEER 18
#define JOB_DISPLAY_ORDER_STATION_ENGINEER 19
#define JOB_DISPLAY_ORDER_ATMOSPHERIC_TECHNICIAN 20
#define JOB_DISPLAY_ORDER_CHIEF_MEDICAL_OFFICER 21
#define JOB_DISPLAY_ORDER_MEDICAL_DOCTOR 22
#define JOB_DISPLAY_ORDER_PARAMEDIC 23
#define JOB_DISPLAY_ORDER_CHEMIST 24
#define JOB_DISPLAY_ORDER_VIROLOGIST 25
#define JOB_DISPLAY_ORDER_GENETICIST 26
#define JOB_DISPLAY_ORDER_RESEARCH_DIRECTOR 27
#define JOB_DISPLAY_ORDER_SCIENTIST 28
#define JOB_DISPLAY_ORDER_ROBOTICIST 29
#define JOB_DISPLAY_ORDER_HEAD_OF_SECURITY 30
#define JOB_DISPLAY_ORDER_WARDEN 31
//#define JOB_DISPLAY_ORDER_DETECTIVE 32
#define JOB_DISPLAY_ORDER_SECURITY_OFFICER 33

#define JOB_DISPLAY_ORDER_NCR_OFF_DUTY 34
#define JOB_DISPLAY_ORDER_CAPTAIN_NCR 35
#define JOB_DISPLAY_ORDER_LIEUTENANT 36
#define JOB_DISPLAY_ORDER_FIRSTSERGEANT 37
#define JOB_DISPLAY_ORDER_SERGEANT 38
#define JOB_DISPLAY_ORDER_CORPORAL 39
#define JOB_DISPLAY_ORDER_SPECIALIST 40
#define JOB_DISPLAY_ORDER_TROOPER 41
#define JOB_DISPLAY_ORDER_REAR_ECHELON 42
#define JOB_DISPLAY_ORDER_VETRANGE 43
#define JOB_DISPLAY_ORDER_RANGER 44

#define JOB_DISPLAY_ORDER_CENTURION 45
#define JOB_DISPLAY_ORDER_ORATOR 46
#define JOB_DISPLAY_ORDER_PRIESTESS 47
#define JOB_DISPLAY_ORDER_DECANREC 48
#define JOB_DISPLAY_ORDER_DECAN 49
#define JOB_DISPLAY_ORDER_DECANVET 50
#define JOB_DISPLAY_ORDER_VEXILLARIUS 51
#define JOB_DISPLAY_ORDER_EXPLORER 52
#define JOB_DISPLAY_ORDER_VENATOR 53
#define JOB_DISPLAY_ORDER_VETLEGIONARY 54
#define JOB_DISPLAY_ORDER_LEGIONARY 55
#define JOB_DISPLAY_ORDER_RECRUITLEG 56
#define JOB_DISPLAY_ORDER_AUXILIA 57
#define JOB_DISPLAY_ORDER_LEGIONSLAVE 58
#define JOB_DISPLAY_ORDER_SLAVEMASTER 59

#define JOB_DISPLAY_ORDER_SENTINEL 60
#define JOB_DISPLAY_ORDER_SENIORPALADIN 61
#define JOB_DISPLAY_ORDER_PALADIN 62
#define JOB_DISPLAY_ORDER_KNIGHTCAPTAIN 63
#define JOB_DISPLAY_ORDER_SENIORKNIGHT 64
#define JOB_DISPLAY_ORDER_KNIGHT 65
#define JOB_DISPLAY_ORDER_HEADSCRIBE 66
#define JOB_DISPLAY_ORDER_SENIORSCRIBE 67
#define JOB_DISPLAY_ORDER_SCRIBE 68
#define JOB_DISPLAY_ORDER_INITIATE 69
#define JOB_DISPLAY_ORDER_OFFDUTYBOS 70

#define JOB_DISPLAY_ORDER_SHERIFF 71
#define JOB_DISPLAY_ORDER_DENDOC 72
#define JOB_DISPLAY_ORDER_SETTLER 73
#define JOB_DISPLAY_ORDER_FARMER 74
#define JOB_DISPLAY_ORDER_PROSPECTOR 75
#define JOB_DISPLAY_ORDER_DEPUTY 76
#define JOB_DISPLAY_ORDER_MAYOR 77
#define JOB_DISPLAY_ORDER_PREACHER 78
#define JOB_DISPLAY_ORDER_SHOPKEEPER 79
#define JOB_DISPLAY_ORDER_FAITHFUL 80// WHAT IS BITFLAG. WHAT DOES IT DO. WHERE IS THIS INFO USED.
#define JOB_DISPLAY_ORDER_BANKER 81// IDK MAN BUT IT SEEMS IMPORTANT
#define JOB_DISPLAY_ORDER_BARKEEP 82


#define JOB_DISPLAY_ORDER_OVERSEER 83
#define JOB_DISPLAY_ORDER_HOS 84
#define JOB_DISPLAY_ORDER_DOCTOR 85
#define JOB_DISPLAY_ORDER_VAULTSCIENTIST 86
#define JOB_DISPLAY_ORDER_OFFICER 87
#define JOB_DISPLAY_ORDER_VAULTENGINEER 88
#define JOB_DISPLAY_ORDER_DWELLER 89
#define JOB_DISPLAY_ORDER_AI 90
#define JOB_DISPLAY_ORDER_CYBORG 91


#define JOB_DISPLAY_ORDER_CULTLEADER 92
#define JOB_DISPLAY_ORDER_WASTELANDER 93
#define JOB_DISPLAY_ORDER_RAIDER 94
#define JOB_DISPLAY_ORDER_PUSHER 95
#define JOB_DISPLAY_ORDER_PUNRAIDER 96
#define JOB_DISPLAY_ORDER_DETECTIVE 97

#define JOB_DISPLAY_ORDER_CHIEF 98
#define JOB_DISPLAY_ORDER_SHAMAN 99
#define JOB_DISPLAY_ORDER_HHUNTER 100
#define JOB_DISPLAY_ORDER_VILLAGER 101
#define JOB_DISPLAY_ORDER_HUNTER 102


#define	JOB_DISPLAY_ORDER_LEADPRACTITIONER 103
#define	JOB_DISPLAY_ORDER_PRACTITIONER 104
#define JOB_DISPLAY_ORDER_FOLLOWERGUARD 105
#define JOB_DISPLAY_ORDER_FOLLOWERVOLUNTEER 106
#define JOB_DISPLAY_ORDER_PROFESSOR 107
