#define PI_MASTER                 "master"
#define PI_CKEY                   "ckey"
#define PI_NAME                   "name"
#define PI_VISIBILITY             "visibility"
#define PI_ONLINE                 "online"
#define PI_SPECIES                "species"
#define PI_FLAVOR_TEXT            "flavor_text"
#define PI_OOC_TEXT               "ooc_text"
#define PI_ADVENTURE_NOTES        "adventure_notes"
#define PI_ADVENTURE_I_AM_A       "adventure_i_am_a"
#define PI_ADVENTURE_LOOKING_FOR  "adventure_looking_for"
#define PI_ADVENTURE_IN_IT_FOR    "adventure_in_it_for"
#define PI_ADVENTURE_LISTING_KIND "adventure_listing_kind"
#define PI_ADVENTURE_IS_HEALER    "adventure_is_healer"
#define PI_ADVENTURE_LFG          "adventure_lfg"
#define PI_ADVENTURE_PVP_PREF     "adventure_pvp_pref"
#define PI_RP_NOTES               "rp_notes"
#define PI_RP_JOB                 "rp_job"
#define PI_RP_I_AM_A              "rp_i_am_a"
#define PI_RP_LOOKING_FOR         "rp_looking_for"
#define PI_RP_LISTING_KIND        "rp_listing_kind"
#define PI_RP_APPROACH_PREF       "rp_approach_pref"
#define PI_RP_LIKES               "rp_likes"
#define PI_RP_DISLIKES            "rp_dislikes"
#define PI_RP_LENGTH              "rp_length"
#define PI_ERP_NOTES              "erp_notes"
#define PI_ERP_LIKES              "erp_likes"
#define PI_ERP_DISLIKES           "erp_dislikes"
#define PI_ERP_I_AM_A             "erp_i_am_a"
#define PI_ERP_LOOKING_FOR        "erp_looking_for"
#define PI_ERP_LISTING_KIND       "erp_listing_kind"
#define PI_ERP_APPROACH_PREF      "erp_approach_pref"
#define PI_ERP_LENGTH             "erp_length"
#define PI_ERP_POST_LENGTH        "erp_post_length"
#define PI_ERP_SEXUALITY          "erp_sexuality"
#define PI_ERP_SEX                "erp_sex"
#define PI_ERP_GENDER             "erp_gender"
#define PI_ERP_POSITION           "erp_position"
#define PI_ERP_VORE               "erp_vore

#define PI_KIND_MISC           "Misc"
#define PI_KIND_PLAYER         "Player"
#define PI_KIND_ADVENTURE      "Adventure"
#define PI_KIND_RP             "RP"
#define PI_KIND_ERP            "ERP"

#define RP_LENGTH_DEFAULT     "Any"
#define RP_PREF_DEFAULT       "Any"
#define ERP_LENGTH_DEFAULT    "Any"
#define ERP_TYPE_DEFAULT      "Any"
#define ERP_POSITION_DEFAULT  "Switch"
#define LISTING_KIND_DEFAULT  "Your call"
#define APPROACH_PREF_DEFAULT "Say hi to me!"
#define ADVENTURE_IN_IT_FOR_DEFAULT "The friends we make along the way."

