#define STAT_STR "Brawn"
#define STAT_PER "Awareness"
#define STAT_END "Toughness"
#define STAT_CHA "Moxie"
#define STAT_INT "Smarts"
#define STAT_AGI "Deftness"
#define STAT_LCK "Fate"
#define STAT_GEN "Flat Roll"
#define STAT_SUF "Crit"
