/*
 If someone decides to name a var slot_flags
 outside of /obj/item, I will find you.
 (this sort of bitfield definition will ALWAYS
 use this menu so you can't var edit normally)
*/

#define DEFINE_BITFIELD(_variable, _flags) /datum/bitfield/##_variable { \
	flags = ##_flags; \
	variable = #_variable; \
}
//lmao

DEFINE_BITFIELD(flags_inv, list(
	"HIDEACCESSORY" = HIDEACCESSORY,
	"HIDEEARS" = HIDEEARS,
	"HIDEEYES" = HIDEEYES,
	"HIDEFACE" = HIDEFACE,
	"HIDEFACIALHAIR" = HIDEFACIALHAIR,
	"HIDEGLOVES" = HIDEGLOVES,
	"HIDEHAIR" = HIDEHAIR,
	"HIDEJUMPSUIT" = HIDEJUMPSUIT,
	"HIDEMASK" = HIDEMASK,
	"HIDENECK" = HIDENECK,
	"HIDESHOES" = HIDESHOES,
	"HIDESNOUT" = HIDESNOUT,
	"HIDESUITSTORAGE" = HIDESUITSTORAGE,
	"HIDETAUR" = HIDETAUR,
	/*
	"HIDEUNDERWEAR" = HIDEUNDERWEAR,
	"HIDEWRISTS" = HIDEWRISTS,
	*/
))
/*
DEFINE_BITFIELD(slot_flags, list(
//	"INV_SLOTBIT_ACCESSORY" = SLOT_ACCESSORY,
	"INV_SLOTBIT_BACK" = SLOT_BACK,
//	"INV_SLOTBIT_BACKPACK" = SLOT_BACKPACK,
	"INV_SLOTBIT_BELT" = SLOT_BELT,
//	"INV_SLOTBIT_DEX_STORAGE" = SLOT_DEX_STORAGE,
	"INV_SLOTBIT_EARS_LEFT" = SLOT_EARS_LEFT,
	"INV_SLOTBIT_EARS_RIGHT" = SLOT_EARS_RIGHT,
	"INV_SLOTBIT_EYES" = SLOT_GLASSES,
	"INV_SLOTBIT_FEET" = SLOT_SHOES,
	"INV_SLOTBIT_GLOVES" = SLOT_GLOVES,
	"INV_SLOTBIT_HANDCUFFED" = SLOT_HANDCUFFED,
	"INV_SLOTBIT_HANDS" = SLOT_HANDS,
	"INV_SLOTBIT_HEAD" = SLOT_HEAD,
	"INV_SLOTBIT_ICLOTHING" = SLOT_ICLOTHING,
	"INV_SLOTBIT_ID" = SLOT_ID,
	"INV_SLOTBIT_LEGCUFFED" = SLOT_LEGCUFFED,
	"INV_SLOTBIT_LPOCKET" = SLOT_L_STORE,
	"INV_SLOTBIT_MASK" = SLOT_MASK,
	"INV_SLOTBIT_NECK" = SLOT_NECK,
	"INV_SLOTBIT_OCLOTHING" = SLOT_OCLOTHING,
	"INV_SLOTBIT_RPOCKET" = SLOT_R_STORE,
	"INV_SLOTBIT_SHIRT" = SLOT_SHIRT,
	"INV_SLOTBIT_SOCKS" = SLOT_SOCKS,
	"INV_SLOTBIT_SUITSTORE" = SLOT_S_STORE,
//	"INV_SLOTBIT_UNDERWEAR" = SLOT_UNDERWEAR,
//	"INV_SLOTBIT_WRISTS" = SLOT_WRISTS,
))

DEFINE_BITFIELD(vis_flags_inv, list(
	"HIDEACCESSORY" = HIDEACCESSORY,
	"HIDEEARS" = HIDEEARS,
	"HIDEEYES" = HIDEEYES,
	"HIDEFACE" = HIDEFACE,
	"HIDEFACIALHAIR" = HIDEFACIALHAIR,
	"HIDEGLOVES" = HIDEGLOVES,
	"HIDEHAIR" = HIDEHAIR,
	"HIDEJUMPSUIT" = HIDEJUMPSUIT,
	"HIDEMASK" = HIDEMASK,
	"HIDENECK" = HIDENECK,
	"HIDESHOES" = HIDESHOES,
	"HIDESNOUT" = HIDESNOUT,
	"HIDESUITSTORAGE" = HIDESUITSTORAGE,
	"HIDETAUR" = HIDETAUR,
//	"HIDEUNDERWEAR" = HIDEUNDERWEAR,
//	"HIDEWRISTS" = HIDEWRISTS,
))
*/
