/*
 If someone decides to name a var slot_flags
 outside of /obj/item, I will find you.
 (this sort of bitfield definition will ALWAYS
 use this menu so you can't var edit normally)
*/

#define DEFINE_BITFIELD(_variable, _flags) /datum/bitfield/##_variable { \
	flags = ##_flags; \
	variable = #_variable; \
}
//lmao

DEFINE_BITFIELD(flags_inv, list(
	"HIDEACCESSORY" = HIDEACCESSORY,
	"HIDEEARS" = HIDEEARS,
	"HIDEEYES" = HIDEEYES,
	"HIDEFACE" = HIDEFACE,
	"HIDEFACIALHAIR" = HIDEFACIALHAIR,
	"HIDEGLOVES" = HIDEGLOVES,
	"HIDEHAIR" = HIDEHAIR,
	"HIDEJUMPSUIT" = HIDEJUMPSUIT,
	"HIDEMASK" = HIDEMASK,
	"HIDENECK" = HIDENECK,
	"HIDESHOES" = HIDESHOES,
	"HIDESNOUT" = HIDESNOUT,
	"HIDESUITSTORAGE" = HIDESUITSTORAGE,
	"HIDETAUR" = HIDETAUR,
	"HIDEUNDERWEAR" = HIDEUNDERWEAR,
	"HIDEWRISTS" = HIDEWRISTS,
))

DEFINE_BITFIELD(slot_flags, list(
	"ITEM_SLOT_ACCESSORY" = ITEM_SLOT_ACCESSORY,
	"ITEM_SLOT_BACK" = ITEM_SLOT_BACK,
	"ITEM_SLOT_BACKPACK" = ITEM_SLOT_BACKPACK,
	"ITEM_SLOT_BELT" = ITEM_SLOT_BELT,
	"ITEM_SLOT_DEX_STORAGE" = ITEM_SLOT_DEX_STORAGE,
	"ITEM_SLOT_EARS_LEFT" = ITEM_SLOT_EARS_LEFT,
	"ITEM_SLOT_EARS_RIGHT" = ITEM_SLOT_EARS_RIGHT,
	"ITEM_SLOT_EYES" = ITEM_SLOT_EYES,
	"ITEM_SLOT_FEET" = ITEM_SLOT_FEET,
	"ITEM_SLOT_GLOVES" = ITEM_SLOT_GLOVES,
	"ITEM_SLOT_HANDCUFFED" = ITEM_SLOT_HANDCUFFED,
	"ITEM_SLOT_HANDS" = ITEM_SLOT_HANDS,
	"ITEM_SLOT_HEAD" = ITEM_SLOT_HEAD,
	"ITEM_SLOT_ICLOTHING" = ITEM_SLOT_ICLOTHING,
	"ITEM_SLOT_ID" = ITEM_SLOT_ID,
	"ITEM_SLOT_LEGCUFFED" = ITEM_SLOT_LEGCUFFED,
	"ITEM_SLOT_LPOCKET" = ITEM_SLOT_LPOCKET,
	"ITEM_SLOT_MASK" = ITEM_SLOT_MASK,
	"ITEM_SLOT_NECK" = ITEM_SLOT_NECK,
	"ITEM_SLOT_OCLOTHING" = ITEM_SLOT_OCLOTHING,
	"ITEM_SLOT_RPOCKET" = ITEM_SLOT_RPOCKET,
	"ITEM_SLOT_SHIRT" = ITEM_SLOT_SHIRT,
	"ITEM_SLOT_SOCKS" = ITEM_SLOT_SOCKS,
	"ITEM_SLOT_SUITSTORE" = ITEM_SLOT_SUITSTORE,
	"ITEM_SLOT_UNDERWEAR" = ITEM_SLOT_UNDERWEAR,
	"ITEM_SLOT_WRISTS" = ITEM_SLOT_WRISTS,
))

DEFINE_BITFIELD(vis_flags_inv, list(
	"HIDEACCESSORY" = HIDEACCESSORY,
	"HIDEEARS" = HIDEEARS,
	"HIDEEYES" = HIDEEYES,
	"HIDEFACE" = HIDEFACE,
	"HIDEFACIALHAIR" = HIDEFACIALHAIR,
	"HIDEGLOVES" = HIDEGLOVES,
	"HIDEHAIR" = HIDEHAIR,
	"HIDEJUMPSUIT" = HIDEJUMPSUIT,
	"HIDEMASK" = HIDEMASK,
	"HIDENECK" = HIDENECK,
	"HIDESHOES" = HIDESHOES,
	"HIDESNOUT" = HIDESNOUT,
	"HIDESUITSTORAGE" = HIDESUITSTORAGE,
	"HIDETAUR" = HIDETAUR,
	"HIDEUNDERWEAR" = HIDEUNDERWEAR,
	"HIDEWRISTS" = HIDEWRISTS,
))
