name: Autobuild TGUI

on:
  push:
    branches:
      - 'master'
    paths:
      - 'tgui/**.js'
      - 'tgui/**.scss'

jobs:
  build:
    name: Rebuild TGUI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 25
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '^18'
      - name: Build TGUI
        run: bin/tgui --build
        working-directory: ./tgui
      - name: Commit Artifacts
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "TGUI"
          git pull origin master
          git commit -m "Automatic TGUI Rebuild [ci skip]" -a || true
      - name: Push Artifacts
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
          branch: protected
